export const TRADE_CSV_HEADERS = [
  "timestamp_utc",
  "order_type",
  "event_name",
  "status",
  "market_name",
  "is_long",
  "chain",
  "reason",
  "data_completeness",
  "manual_review_reason",
  "size_delta_usd",
  "size_delta_tokens",
  "position_size_usd",
  "position_size_tokens",
  "collateral_delta_amount",
  "collateral_delta_usd",
  "trigger_price",
  "acceptable_price",
  "execution_price",
  "contract_trigger_price",
  "input_amount",
  "input_token_symbol",
  "output_amount",
  "output_token_symbol",
  "min_output_amount",
  "execution_amount_out",
  "swap_path",
  "sent_amount",
  "sent_currency",
  "received_amount",
  "received_currency",
  "usd_valuation",
  "valuation_source",
  "base_pnl_usd",
  "net_action_result_usd",
  "position_price_impact_usd",
  "swap_price_impact_usd",
  "pending_price_impact_usd",
  "position_fee_amount",
  "position_fee_usd",
  "borrowing_fee_amount",
  "borrowing_fee_usd",
  "funding_fee_amount",
  "funding_fee_usd",
  "liquidation_fee_amount",
  "liquidation_fee_usd",
  "swap_fee_amount",
  "swap_fee_usd",
  "ui_fee_amount",
  "ui_fee_usd",
  "trader_discount_amount",
  "trader_discount_usd",
  "referral_discount_usd",
  "pro_discount_usd",
  "execution_fee_paid_native",
  "execution_fee_refund_native",
  "execution_fee_currency",
  "wallet_gas_fee_native",
  "index_token_symbol",
  "index_token_address",
  "collateral_token_symbol",
  "collateral_token_address",
  "input_token_address",
  "output_token_address",
  "sent_token_address",
  "received_token_address",
  "market_address",
  "decrease_swap_type",
  "account",
  "transaction_hash",
  "explorer_url",
  "chain_id",
  "log_index",
  "src_chain_id",
  "order_key",
  "position_key",
  "position_lifecycle_id",
  "twap_group_id",
  "twap_part",
  "twap_parts_total",
  "reason_bytes",
  "schema_version",
  "record_id",
  "action_id",
  "row_type",
  "leg_index",
] as const;

export const CLAIMS_CSV_HEADERS = [
  "timestamp_utc",
  "event_name",
  "status",
  "market_name",
  "is_long",
  "token_symbol",
  "amount",
  "token_price_usd",
  "amount_usd",
  "chain",
  "reason",
  "data_completeness",
  "manual_review_reason",
  "index_token_symbol",
  "token_address",
  "index_token_address",
  "market_address",
  "account",
  "transaction_hash",
  "explorer_url",
  "chain_id",
  "log_index",
  "reason_bytes",
  "schema_version",
  "record_id",
  "claim_action_id",
  "leg_index",
] as const;

export const KOINLY_CSV_HEADERS = [
  "Date",
  "Sent Amount",
  "Sent Currency",
  "Received Amount",
  "Received Currency",
  "Fee Amount",
  "Fee Currency",
  "Tags",
  "TxHash",
  "Description",
] as const;

export const COINTRACKER_CSV_HEADERS = [
  "Date",
  "Received Quantity",
  "Received Currency",
  "Sent Quantity",
  "Sent Currency",
  "Fee Amount",
  "Fee Currency",
  "Tag",
] as const;

export const COINLEDGER_UNIVERSAL_CSV_HEADERS = [
  "Date (UTC)",
  "Platform",
  "Asset Sent",
  "Amount Sent",
  "Asset Received",
  "Amount Received",
  "Fee Currency",
  "Fee Amount",
  "Type",
  "Description",
  "TxHash",
] as const;

export const COINLEDGER_MARGIN_CSV_HEADERS = [
  "Date (UTC)",
  "Platform",
  "Result",
  "Asset",
  "Amount",
  "Net Worth USD",
  "Source Event",
  "Market",
  "Position Side",
  "Description",
  "TxHash",
  "GMX Record ID",
  "Entry Method",
] as const;

export const HISTORY_EXPORT_SCHEMA_VERSION = 1;

export type TradeCsvHeader = (typeof TRADE_CSV_HEADERS)[number];
export type ClaimsCsvHeader = (typeof CLAIMS_CSV_HEADERS)[number];
