import { t } from '@lingui/macro';
import { useLingui } from '@lingui/react';
import { useState } from 'react';
import IconUp from '@/img/referrals/up.svg';
import './directions.scss';

export default function ReferralsDirections() {
  const { i18n } = useLingui();
  const [expandedIndexes, setExpandedIndexes] = useState<Set<number>>(new Set());

  const remark = [
    {
      title: t`1. 10% Fee Discount for Referees`,
      description: [
        t`Your referees automatically receive a 10% trading fee discount on all their trades.`,
        t`The discount is applied instantly and continues as long as they trade on GMTrade.`,
      ],
    },
    {
      title: t`2. Earn GT From Your Referees' Activity`,
      description: [
        t`You earn a percentage of the GT rewards generated by your referees.`,
        t`Your reward rate ranges from 50% to 100%, depending on your VIP level.`,
        t`Example: If your referee earns 10 GT in rewards and your reward rate is 70%, you receive 7 GT as a bonus.`,
      ],
    },
    {
      title: t`3. VIP Levels Are Based on Your GT Holdings`,
      description: [
        t`Your VIP level increases as you accumulate and hold more GT.`,
        t`Higher levels unlock greater trading fee discounts and higher referral reward rates.`,
      ],
    },
    {
      title: t`4. Rewards Are Distributed Automatically`,
      description: [
        t`All GT earned from referees goes straight to your GT wallet in real time — no claiming needed.`,
      ],
    },
  ];

  const toggleExpand = (index: number) => {
    const newExpandedIndexes = new Set(expandedIndexes);
    if (newExpandedIndexes.has(index)) {
      newExpandedIndexes.delete(index);
    } else {
      newExpandedIndexes.add(index);
    }
    setExpandedIndexes(newExpandedIndexes);
  };

  return (
    <div
      key={i18n.locale}
      className="directions rounded-[0.8rem] bg-[#181818] p-[2rem] max-w-[60rem]"
    >
      <p className="text-[1.6rem] directions-card-title font-[500] leading-[2.8rem]">
        {t`How Referral Rewards Work`}
      </p>
      <div className="flex  justify-between">
        <div className="mt-[1.6rem] w-full directions-items">
          {remark.map((item, index) => (
            <div key={index} className="border-b-[0.1rem] border-[#535353]  down-menu">
              <div
                className="py-[1.1rem] flex items-center justify-between leading-[1.8rem] cursor-pointer text-[#fff] "
                onClick={() => toggleExpand(index)}
              >
                <span className="text-[1.4rem] font-[500] directions-title">{item.title}</span>
                <img
                  className={`mx-[0.8rem] transition-transform duration-300 cursor-pointer ${
                    expandedIndexes.has(index) ? '' : 'rotate-180'
                  }`}
                  src={IconUp}
                  width={16}
                  height={16}
                  alt="toggle"
                />
              </div>
              <div
                className={`description-content ${expandedIndexes.has(index) ? 'expanded' : 'collapsed'}`}
              >
                {item.description.map((desc, descIndex) => (
                  <p
                    key={descIndex}
                    className="text-[1.3rem] font-[400] leading-[1.7rem] text-[#A3A3A3] pr-[0.5rem]"
                  >
                    {desc}
                  </p>
                ))}
              </div>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}
