import { Trans, t } from "@lingui/macro";

import PageTitle from "components/PageTitle/PageTitle";

export function DashboardPageTitle({ tradePageVersion }: { tradePageVersion: number }) {
  return (
    <PageTitle
      title={t`Tokens`}
      subtitle={
        tradePageVersion === 1 ? (
          <>
            <Trans>
              GMX is the utility and governance token. It also accrues 27% of the protocol fees via a buyback and
              distribution mechanism.
            </Trans>
            <br />
            <Trans>
              GLP is the liquidity provider token for GMX V1 markets. It accrues 70% of fees generated by V1 markets.
            </Trans>
          </>
        ) : (
          <>
            <Trans>
              GMX is the utility and governance token. It also accrues 27% of the protocol fees via a buyback and
              distribution mechanism.
            </Trans>
            <br />
            <Trans>
              GM is the liquidity provider token for GMX V2 markets. It accrues 63% of fees generated by V2 markets.
            </Trans>
          </>
        )
      }
    />
  );
}
