/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type { RelayParams, RelayParamsInterface } from "../RelayParams";

const _abi = [
  {
    components: [
      {
        internalType: "address[]",
        name: "tokens",
        type: "address[]",
      },
      {
        internalType: "address[]",
        name: "providers",
        type: "address[]",
      },
      {
        internalType: "bytes[]",
        name: "data",
        type: "bytes[]",
      },
    ],
    internalType: "struct OracleUtils.SetPricesParams",
    name: "oracleParams",
    type: "tuple",
  },
  {
    components: [
      {
        internalType: "address[]",
        name: "sendTokens",
        type: "address[]",
      },
      {
        internalType: "uint256[]",
        name: "sendAmounts",
        type: "uint256[]",
      },
      {
        internalType: "address[]",
        name: "externalCallTargets",
        type: "address[]",
      },
      {
        internalType: "bytes[]",
        name: "externalCallDataList",
        type: "bytes[]",
      },
      {
        internalType: "address[]",
        name: "refundTokens",
        type: "address[]",
      },
      {
        internalType: "address[]",
        name: "refundReceivers",
        type: "address[]",
      },
    ],
    internalType: "struct ExternalCalls",
    name: "externalCalls",
    type: "tuple",
  },
  {
    components: [
      {
        internalType: "address",
        name: "owner",
        type: "address",
      },
      {
        internalType: "address",
        name: "spender",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "value",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "deadline",
        type: "uint256",
      },
      {
        internalType: "uint8",
        name: "v",
        type: "uint8",
      },
      {
        internalType: "bytes32",
        name: "r",
        type: "bytes32",
      },
      {
        internalType: "bytes32",
        name: "s",
        type: "bytes32",
      },
      {
        internalType: "address",
        name: "token",
        type: "address",
      },
    ],
    internalType: "struct TokenPermit[]",
    name: "tokenPermits",
    type: "tuple[]",
  },
  {
    components: [
      {
        internalType: "address",
        name: "feeToken",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "feeAmount",
        type: "uint256",
      },
      {
        internalType: "address[]",
        name: "feeSwapPath",
        type: "address[]",
      },
    ],
    internalType: "struct FeeParams",
    name: "fee",
    type: "tuple",
  },
  {
    internalType: "uint256",
    name: "userNonce",
    type: "uint256",
  },
  {
    internalType: "uint256",
    name: "deadline",
    type: "uint256",
  },
  {
    internalType: "uint256",
    name: "desChainId",
    type: "uint256",
  },
] as const;

export class RelayParams__factory {
  static readonly abi = _abi;
  static createInterface(): RelayParamsInterface {
    return new Interface(_abi) as RelayParamsInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): RelayParams {
    return new Contract(address, _abi, runner) as unknown as RelayParams;
  }
}
