query GetAccountPerformance(
  $first: Int = 10,
  $skip: Int = 0,
  $orderBy: AccountPerf_orderBy = totalPnl,
  $orderDirection: OrderDirection = desc,
  $period: Period = daily,
  $since: Int = 0,
) {
  accountPerfs(
    first: $first,
    skip: $skip,
    orderBy: $orderBy,
    orderDirection: $orderDirection,
    where: { timestamp_gte: $since, period: $period }
  ) {
    id
    account
    period
    timestamp
    wins
    losses
    totalPnl
    totalCollateral
    maxCollateral
    cumsumSize
    cumsumCollateral
    sumMaxSize
    closedCount
  }
}
