query GetAccountOpenPositions(
  $first: Int,
  $skip: Int = 0,
  $orderBy: AccountOpenPosition_orderBy = sizeInUsd,
  $orderDirection: OrderDirection = desc,
) {
  accountOpenPositions(
    first: $first,
    skip: $skip,
    orderBy: $orderBy,
    orderDirection: $orderDirection
  ) {
    id
    account
    market
    collateralToken
    isLong
    realizedPnl
    sizeInTokens
    sizeInUsd
    entryPrice
    maxSize
  }
}
