/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type { ReferralUtilsCopy, ReferralUtilsCopyInterface } from "../ReferralUtilsCopy";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "key",
        type: "bytes32",
      },
    ],
    name: "DisabledFeature",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "marketsLength",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "tokensLength",
        type: "uint256",
      },
    ],
    name: "InvalidClaimAffiliateRewardsInput",
    type: "error",
  },
] as const;

export class ReferralUtilsCopy__factory {
  static readonly abi = _abi;
  static createInterface(): ReferralUtilsCopyInterface {
    return new Interface(_abi) as ReferralUtilsCopyInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): ReferralUtilsCopy {
    return new Contract(address, _abi, runner) as unknown as ReferralUtilsCopy;
  }
}
