/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type { TypedEventFilter, TypedEvent, TypedListener, OnEvent, PromiseOrValue } from "../../common";

export declare namespace Deposit {
  export type AddressesStruct = {
    account: PromiseOrValue<string>;
    receiver: PromiseOrValue<string>;
    callbackContract: PromiseOrValue<string>;
    market: PromiseOrValue<string>;
  };

  export type AddressesStructOutput = [string, string, string, string] & {
    account: string;
    receiver: string;
    callbackContract: string;
    market: string;
  };

  export type NumbersStruct = {
    longTokenAmount: PromiseOrValue<BigNumberish>;
    shortTokenAmount: PromiseOrValue<BigNumberish>;
    minMarketTokens: PromiseOrValue<BigNumberish>;
    updatedAtBlock: PromiseOrValue<BigNumberish>;
    executionFee: PromiseOrValue<BigNumberish>;
    callbackGasLimit: PromiseOrValue<BigNumberish>;
  };

  export type NumbersStructOutput = [BigNumber, BigNumber, BigNumber, BigNumber, BigNumber, BigNumber] & {
    longTokenAmount: BigNumber;
    shortTokenAmount: BigNumber;
    minMarketTokens: BigNumber;
    updatedAtBlock: BigNumber;
    executionFee: BigNumber;
    callbackGasLimit: BigNumber;
  };

  export type FlagsStruct = {
    shouldUnwrapNativeToken: PromiseOrValue<boolean>;
  };

  export type FlagsStructOutput = [boolean] & {
    shouldUnwrapNativeToken: boolean;
  };

  export type PropsStruct = {
    addresses: Deposit.AddressesStruct;
    numbers: Deposit.NumbersStruct;
    flags: Deposit.FlagsStruct;
    data: PromiseOrValue<BytesLike>;
  };

  export type PropsStructOutput = [
    Deposit.AddressesStructOutput,
    Deposit.NumbersStructOutput,
    Deposit.FlagsStructOutput,
    string
  ] & {
    addresses: Deposit.AddressesStructOutput;
    numbers: Deposit.NumbersStructOutput;
    flags: Deposit.FlagsStructOutput;
    data: string;
  };
}

export interface IDepositCallbackReceiverInterface extends utils.Interface {
  functions: {
    "afterDepositCancellation(bytes32,((address,address,address,address),(uint256,uint256,uint256,uint256,uint256,uint256),(bool),bytes))": FunctionFragment;
    "afterDepositExecution(bytes32,((address,address,address,address),(uint256,uint256,uint256,uint256,uint256,uint256),(bool),bytes))": FunctionFragment;
    "beforeDepositExecution(bytes32,((address,address,address,address),(uint256,uint256,uint256,uint256,uint256,uint256),(bool),bytes))": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic: "afterDepositCancellation" | "afterDepositExecution" | "beforeDepositExecution"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "afterDepositCancellation",
    values: [PromiseOrValue<BytesLike>, Deposit.PropsStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "afterDepositExecution",
    values: [PromiseOrValue<BytesLike>, Deposit.PropsStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "beforeDepositExecution",
    values: [PromiseOrValue<BytesLike>, Deposit.PropsStruct]
  ): string;

  decodeFunctionResult(functionFragment: "afterDepositCancellation", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "afterDepositExecution", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "beforeDepositExecution", data: BytesLike): Result;

  events: {};
}

export interface IDepositCallbackReceiver extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IDepositCallbackReceiverInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(eventFilter?: TypedEventFilter<TEvent>): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(eventFilter: TypedEventFilter<TEvent>): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    afterDepositCancellation(
      key: PromiseOrValue<BytesLike>,
      deposit: Deposit.PropsStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    afterDepositExecution(
      key: PromiseOrValue<BytesLike>,
      deposit: Deposit.PropsStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    beforeDepositExecution(
      key: PromiseOrValue<BytesLike>,
      deposit: Deposit.PropsStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  afterDepositCancellation(
    key: PromiseOrValue<BytesLike>,
    deposit: Deposit.PropsStruct,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  afterDepositExecution(
    key: PromiseOrValue<BytesLike>,
    deposit: Deposit.PropsStruct,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  beforeDepositExecution(
    key: PromiseOrValue<BytesLike>,
    deposit: Deposit.PropsStruct,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    afterDepositCancellation(
      key: PromiseOrValue<BytesLike>,
      deposit: Deposit.PropsStruct,
      overrides?: CallOverrides
    ): Promise<void>;

    afterDepositExecution(
      key: PromiseOrValue<BytesLike>,
      deposit: Deposit.PropsStruct,
      overrides?: CallOverrides
    ): Promise<void>;

    beforeDepositExecution(
      key: PromiseOrValue<BytesLike>,
      deposit: Deposit.PropsStruct,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    afterDepositCancellation(
      key: PromiseOrValue<BytesLike>,
      deposit: Deposit.PropsStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    afterDepositExecution(
      key: PromiseOrValue<BytesLike>,
      deposit: Deposit.PropsStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    beforeDepositExecution(
      key: PromiseOrValue<BytesLike>,
      deposit: Deposit.PropsStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    afterDepositCancellation(
      key: PromiseOrValue<BytesLike>,
      deposit: Deposit.PropsStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    afterDepositExecution(
      key: PromiseOrValue<BytesLike>,
      deposit: Deposit.PropsStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    beforeDepositExecution(
      key: PromiseOrValue<BytesLike>,
      deposit: Deposit.PropsStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
