// Source: gmx-solana-interface/app/src/config/program.ts (GMX_SOLANA_STORE_ADDRESS, GMX_SOLANA_TOKENS_RAW mainnet branch).
// Nightly-gated tokens from the reference (XCU, XPT, XPD) are included unconditionally: this table is only
// used to resolve symbol / decimals for positions that already exist on chain.

/** GMTrade store account. Every market / position account of the deployment references it. */
export const GMX_SOLANA_STORE_ADDRESS = "CTDLvGGXnoxvqLyTpGzdGLg9pD6JexKxKXSV8tqqo8bN";

/** gmsol_store program id. Must match `address` in solana-interface/src/idl/gmsol_store.json. */
export const GMX_SOLANA_STORE_PROGRAM_ID = "Gmso1uvJnLbawvw7yezdfCDcPydwW2s2iqG3w6MDucLo";

/** GMTrade USD values carry 20 decimals (GMX EVM uses 30). */
export const GMTRADE_USD_DECIMALS = 20;
export const ONE_GMTRADE_USD = 10n ** BigInt(GMTRADE_USD_DECIMALS);

export type SolanaTokenType = "crypto" | "stock" | "forex" | "commodity" | "spot";

export type SolanaTokenConfig = {
  symbol: string;
  type?: SolanaTokenType;
  displaySymbol?: string;
  displayMarketName?: string;
  candleMarketName?: string;
  decimals: number;
  decimals_gmx?: number;
  isStable?: boolean;
  isSynthetic?: boolean;
  isNative?: boolean;
  isWrappedNative?: boolean;
  wrappedAddress?: string;
  shouldWrap?: boolean;
  isSpl2022Mint?: boolean;
  tradingHours?: "24/7";
};

/** Token metadata keyed by mint address (base58). */
export const GMX_SOLANA_TOKENS: Record<string, SolanaTokenConfig> = {
  // not dev
  "11111111111111111111111111111111": {
    symbol: "SOL",
    type: "crypto",
    displaySymbol: "SOL",
    decimals: 9,
    decimals_gmx: 9,
    wrappedAddress: "So11111111111111111111111111111111111111112",
    isNative: true,
    isSynthetic: true,
    displayMarketName: "SOL/USD",
  },
  So1Zu7vPQQxrguzUehKAyVLpjcc769zxgBuDAsxTUMH: {
    symbol: "SOL",
    type: "crypto",
    displaySymbol: "SOL",
    decimals: 9,
    decimals_gmx: 9,
    wrappedAddress: "So11111111111111111111111111111111111111112",
    isNative: true,
    displayMarketName: "SOL/USD",
  },
  So11111111111111111111111111111111111111112: {
    symbol: "WSOL",
    type: "crypto",
    displaySymbol: "SOL",
    decimals: 9,
    decimals_gmx: 9,
    isWrappedNative: true,
    displayMarketName: "SOL/USD",
  },
  EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v: {
    symbol: "USDC",
    type: "crypto",
    displaySymbol: "USDC",
    decimals: 6,
    decimals_gmx: 6,
    isStable: true,
    displayMarketName: "USDC/USD",
  },
  Es9vMFrzaCERmJfrF4H2FYD4KCoNkY11McCe8BenwNYB: {
    symbol: "USDT",
    type: "crypto",
    displaySymbol: "USDT",
    decimals: 6,
    decimals_gmx: 6,
    isStable: true,
    displayMarketName: "USDT/USD",
  },
  EKpQGSJtjMFqKZ9KQanSqYXRcF8fBopzLHYxdM65zcjm: {
    symbol: "WIF",
    type: "crypto",
    displaySymbol: "WIF",
    decimals: 6,
    decimals_gmx: 6,
    displayMarketName: "WIF/USD",
  },
  "2wpTofQ8SkACrkZWrZDjXPitYa8AwWgX8AfxdeBRRVLX": {
    symbol: "LINK",
    type: "crypto",
    displaySymbol: "LINK",
    decimals: 8,
    decimals_gmx: 18,
    displayMarketName: "LINK/USD",
  },
  BtcTQYRj7HRRk7MwnWiTFj8rWqN2ALt2QYig4cSWqTbv: {
    symbol: "BTC",
    type: "crypto",
    displaySymbol: "BTC",
    decimals: 8,
    decimals_gmx: 8,
    displayMarketName: "BTC/USD",
    isSynthetic: true,
  },
  "3NZ9JMVBmGAqocybic2c7LQCJScmgsAZ6vQqTDzcqmJh": {
    symbol: "WBTC",
    type: "crypto",
    displaySymbol: "WBTC",
    decimals: 8,
    decimals_gmx: 8,
    displayMarketName: "BTC/USD",
  },
  EthK4kKnQQUd1Ae1w7sdiMAUaJwq2RMwr7AtscXEdEsF: {
    symbol: "ETH",
    type: "crypto",
    displaySymbol: "ETH",
    decimals: 8,
    decimals_gmx: 18,
    displayMarketName: "ETH/USD",
    isSynthetic: true,
  },
  "7vfCXTUXx5WJV5JADk17DUJ4ksgau7utNKj4b963voxs": {
    symbol: "WETH",
    type: "crypto",
    displaySymbol: "WETH",
    decimals: 8,
    decimals_gmx: 18,
    displayMarketName: "ETH/USD",
  },
  ukHH6c7mMyiWCf1b9pnWe25TSpkDDt3H5pQZgZ74J82: {
    symbol: "BOME",
    type: "crypto",
    displaySymbol: "BOME",
    decimals: 6,
    decimals_gmx: 6,
    displayMarketName: "BOME/USD",
  },
  DezXAZ8z7PnrnRJjz3wXBoRgixCa6xjnB7YaB1pPB263: {
    symbol: "BONK",
    type: "crypto",
    displaySymbol: "BONK",
    decimals: 5,
    decimals_gmx: 5,
    displayMarketName: "BONK/USD",
  },
  FUAfBo2jgks6gB4Z4LfZkqSZgzNucisEHqnNebaRxM1P: {
    symbol: "MELANIA",
    type: "crypto",
    displaySymbol: "MELANIA",
    decimals: 6,
    decimals_gmx: 6,
    displayMarketName: "MELANIA/USD",
  },
  "6p6xgHyF7AeE6TZkSmFsko444wqoP15icUSqi2jfGiPN": {
    symbol: "TRUMP",
    type: "crypto",
    displaySymbol: "TRUMP",
    decimals: 6,
    decimals_gmx: 6,
    displayMarketName: "TRUMP/USD",
  },
  "9BB6NFEcjBCtnNLFko2FqVQBq8HHM13kCyYcdQbgpump": {
    symbol: "FARTCOIN",
    type: "crypto",
    displaySymbol: "FARTCOIN",
    decimals: 6,
    decimals_gmx: 6,
    displayMarketName: "FARTCOIN/USD",
  },
  GmxDsqjKYUrwgbvccGrpF1LoyHPUq8FQqT1FJfkvrMfY: {
    symbol: "GMX",
    type: "crypto",
    displaySymbol: "GMX",
    decimals: 9,
    decimals_gmx: 18,
    isSynthetic: true,
    displayMarketName: "GMX/USD",
  },
  DogeJP1vR955QsXWKT1vw5gJsyiTthqPEtJZj8enDWxF: {
    symbol: "DOGE",
    type: "crypto",
    displaySymbol: "DOGE",
    decimals: 8,
    decimals_gmx: 8,
    isSynthetic: true,
    displayMarketName: "DOGE/USD",
  },
  LtcsFqdfsLyoHZ7cRt9BkijqbFRAN1M4fB8naGaykTF: {
    symbol: "LTC",
    type: "crypto",
    displaySymbol: "LTC",
    decimals: 8,
    decimals_gmx: 8,
    isSynthetic: true,
    displayMarketName: "LTC/USD",
  },
  Unicsoj67GbDzQyWXQEh9vG5jBiVhMREtWBVDAFVpQq: {
    symbol: "UNI",
    type: "crypto",
    displaySymbol: "UNI",
    decimals: 8,
    decimals_gmx: 18,
    isSynthetic: true,
    displayMarketName: "UNI/USD",
  },
  XrpSaeAcbKAGv8P3kWbMbwbq8xcWgR548yvyiKKJUB9: {
    symbol: "XRP",
    type: "crypto",
    displaySymbol: "XRP",
    decimals: 6,
    decimals_gmx: 6,
    isSynthetic: true,
    displayMarketName: "XRP/USD",
  },
  BnbuyeSZgnWxXppzkRgiA5TR4t3L9NBRnk6Hbr9m5GsJ: {
    symbol: "BNB",
    type: "crypto",
    displaySymbol: "BNB",
    decimals: 8,
    decimals_gmx: 18,
    isSynthetic: true,
    displayMarketName: "BNB/USD",
  },
  AaveaPPwFJx88apsgcpzck7xkohpiZPViKkNndRZJ6pv: {
    symbol: "AAVE",
    type: "crypto",
    displaySymbol: "AAVE",
    decimals: 8,
    decimals_gmx: 18,
    isSynthetic: true,
    displayMarketName: "AAVE/USD",
  },
  PepeCS5SuDLkUwfnhmBLsPsVdpy9WR5bmXT4dkipR9i: {
    symbol: "PEPE",
    type: "crypto",
    displaySymbol: "PEPE",
    decimals: 5,
    decimals_gmx: 18,
    isSynthetic: true,
    displayMarketName: "PEPE/USD",
  },
  SuiyRuzKdsxGgdhVJGg5dDz6wtNSQUAWN21zSdCmYXs: {
    symbol: "SUI",
    type: "crypto",
    displaySymbol: "SUI",
    decimals: 9,
    decimals_gmx: 9,
    isSynthetic: true,
    displayMarketName: "SUI/USD",
  },
  BchGdYptcKvUDCpHMDAB5h1MfXq2LPzRLcU8b4r8dQiQ: {
    symbol: "BCH",
    type: "crypto",
    displaySymbol: "BCH",
    decimals: 8,
    decimals_gmx: 8,
    isSynthetic: true,
    displayMarketName: "BCH/USD",
  },
  TonDqfXQT4A9oexj8nWdQuUs97Zep5UG5auXByTKe79: {
    symbol: "TON",
    type: "crypto",
    displaySymbol: "TON",
    decimals: 9,
    decimals_gmx: 9,
    isSynthetic: true,
    displayMarketName: "TON/USD",
  },
  KgV1GvrHQmRBY8sHQQeUKwTm2r2h8t4C8qt12Cw1HVE: {
    symbol: "AVAX",
    type: "crypto",
    displaySymbol: "AVAX",
    decimals: 8,
    decimals_gmx: 18,
    isSynthetic: true,
    displayMarketName: "AVAX/USD",
  },
  TrxYuLyf3WbYPrQ84cjyWgfcEeKTc7m5cKBNBZhY5MN: {
    symbol: "TRX",
    type: "crypto",
    displaySymbol: "TRX",
    decimals: 8,
    decimals_gmx: 6,
    isSynthetic: true,
    displayMarketName: "TRX/USD",
  },
  X1mpyVGnE5VhzwbAqLp1FuAW7oY45WPTDisbcEkbVLq: {
    symbol: "XLM",
    type: "crypto",
    displaySymbol: "XLM",
    decimals: 8,
    decimals_gmx: 7,
    isSynthetic: true,
    displayMarketName: "XLM/USD",
  },
  AdamfezT5MsUMv5PtSBDWHwPCpcYVyq2CWAseqNbwU7Q: {
    symbol: "ADA",
    type: "crypto",
    displaySymbol: "ADA",
    decimals: 8,
    decimals_gmx: 6,
    isSynthetic: true,
    displayMarketName: "ADA/USD",
  },
  DotB5VDVP2VbfETfRsEsWnPH42tBiQZxHjGNH4iaNGSR: {
    symbol: "DOT",
    type: "crypto",
    displaySymbol: "DOT",
    decimals: 8,
    decimals_gmx: 10,
    isSynthetic: true,
    displayMarketName: "DOT/USD",
  },
  ShibkCetJam99AeDv93Q4KKVkeLCBSLSmBKNLpwt1ik: {
    symbol: "SHIB",
    type: "crypto",
    displaySymbol: "SHIB",
    decimals: 6,
    decimals_gmx: 18,
    isSynthetic: true,
    displayMarketName: "SHIB/USD",
  },
  pumpCmXqMfrsAkQ5r49WcJnRayYRqmXz6ae8H7H9Dfn: {
    symbol: "PUMP",
    type: "crypto",
    displaySymbol: "PUMP",
    decimals: 6,
    decimals_gmx: 18,
    isSpl2022Mint: true,
    shouldWrap: true,
    wrappedAddress: "HTHR6CbWSqrVCB83onNwKKH1W3qpGoKbpqvs9sgK7PEC",
    displayMarketName: "PUMP/USD",
  },
  HTHR6CbWSqrVCB83onNwKKH1W3qpGoKbpqvs9sgK7PEC: {
    symbol: "WPUMP",
    type: "crypto",
    displaySymbol: "WPUMP",
    decimals: 6,
    decimals_gmx: 18,
    displayMarketName: "PUMP/USD",
  },
  SpyoXYfv2RmbLkURbxyXvxs83PFFNMiirXgZhBAgxBQ: {
    symbol: "SPY",
    type: "stock",
    displaySymbol: "SPY",
    decimals: 8,
    decimals_gmx: 8,
    isSynthetic: true,
    displayMarketName: "SPY/USD",
  },
  Msftix9DNgRjxF7SXjjqfxjusmaXByNnDc6cdX3Z2qu: {
    symbol: "MSFT",
    type: "stock",
    displaySymbol: "MSFT",
    decimals: 8,
    decimals_gmx: 8,
    isSynthetic: true,
    displayMarketName: "MSFT/USD",
  },
  AapaFKgsAsCMqSvXBPXqipX5WWxArgnPbADSNfhU9E9J: {
    symbol: "AAPL",
    type: "stock",
    displaySymbol: "AAPL",
    decimals: 8,
    decimals_gmx: 8,
    isSynthetic: true,
    displayMarketName: "AAPL/USD",
  },
  AmzF1ANXKgmWzm8TLmjAUaZTeqT4gZGV9Xi81yLx1FF9: {
    symbol: "AMZN",
    type: "stock",
    displaySymbol: "AMZN",
    decimals: 8,
    decimals_gmx: 8,
    isSynthetic: true,
    displayMarketName: "AMZN/USD",
  },
  GooBXeDfVwNPMCvHvGvUtEVxt1GwGzXxL8kqv8YKsAAy: {
    symbol: "GOOGL",
    type: "stock",
    displaySymbol: "GOOGL",
    decimals: 8,
    decimals_gmx: 8,
    isSynthetic: true,
    displayMarketName: "GOOGL/USD",
  },
  Metn9UEcTz2oUDL2rBmxrvTvhL2TfYBqvfYnjf1xptt: {
    symbol: "META",
    type: "stock",
    displaySymbol: "META",
    decimals: 8,
    decimals_gmx: 8,
    isSynthetic: true,
    displayMarketName: "META/USD",
  },
  Mst8Wf1EzeQi9pmtuhRoJ85DG7EPzBoa38bayRvNZXb: {
    displaySymbol: "MSTR",
    symbol: "MSTR",
    type: "stock",
    decimals: 8,
    decimals_gmx: 8,
    isSynthetic: true,
    displayMarketName: "MSTR/USD",
  },
  NvdwZ2PeA9HaCnRu59ZmRXGQJfyaRVTVZuxZ79voGWP: {
    symbol: "NVDA",
    type: "stock",
    displaySymbol: "NVDA",
    decimals: 8,
    decimals_gmx: 8,
    isSynthetic: true,
    displayMarketName: "NVDA/USD",
  },
  QqqSrHycWaS3f3o4fvEgeVfXfZbqdchUGB3rGxok9qj: {
    symbol: "QQQ",
    type: "stock",
    displaySymbol: "QQQ",
    decimals: 8,
    decimals_gmx: 8,
    isSynthetic: true,
    displayMarketName: "QQQ/USD",
  },
  Spc8vPRaUMi4KKofgM8duFQRBK58xjS15pdzgioAAhD: {
    symbol: "SPCX",
    type: "stock",
    displaySymbol: "SPCX",
    decimals: 8,
    decimals_gmx: 8,
    isSynthetic: true,
    displayMarketName: "SPCX/USD",
  },
  Ts1F5Xa8WR4mGqpZ35bhDM56MHf7Zzvq3L6dYGXVdk4: {
    symbol: "TSLA",
    type: "stock",
    displaySymbol: "TSLA",
    decimals: 8,
    decimals_gmx: 8,
    displayMarketName: "TSLA/USD",
    isSynthetic: true,
  },
  XagEFqWzJtB3XezX6KLQtGkBQDdTpcXYDG7X3EdMH2Y: {
    symbol: "XAG",
    type: "spot",
    displaySymbol: "XAG",
    decimals: 8,
    decimals_gmx: 8,
    displayMarketName: "XAG/USD",
    isSynthetic: true,
    tradingHours: "24/7",
  },
  Xauxf2VJhbue14FGbp3W8XwfQSECHYpiPMNMWSCwjSR: {
    symbol: "XAU",
    type: "spot",
    displaySymbol: "XAU",
    decimals: 8,
    decimals_gmx: 8,
    displayMarketName: "XAU/USD",
    isSynthetic: true,
    tradingHours: "24/7",
  },
  WLFinEv6ypjkczcS83FZqFpgFZYwQXutRbxGe7oC16g: {
    symbol: "WLFI",
    type: "crypto",
    displaySymbol: "WLFI",
    decimals: 6,
    decimals_gmx: 18,
    displayMarketName: "WLFI/USD",
    isSynthetic: false,
  },
  C1MHyoTJpRTeS9AQCyspNVu2EWAYCZwmJ1jNkEArFP1f: {
    symbol: "APE",
    type: "crypto",
    displaySymbol: "APE",
    decimals: 9,
    decimals_gmx: 18,
    displayMarketName: "APE/USD",
    isSynthetic: false,
  },
  Xp1adJXBj9MhK7hwAbgPN2rhuiK64nfMYTSg9vzgUB2: {
    displaySymbol: "XPL",
    symbol: "XPL",
    type: "crypto",
    decimals: 8,
    decimals_gmx: 18,
    displayMarketName: "XPL/USD",
    isSynthetic: false,
  },
  Ast9jCRDBog1oWQUJbhXbGhiPcjPTgsbPKf3qGK8vixc: {
    displaySymbol: "ASTER",
    symbol: "ASTER",
    type: "crypto",
    decimals: 8,
    decimals_gmx: 18,
    displayMarketName: "ASTER/USD",
    isSynthetic: false,
  },
  EnaRUVoWPozu58p8FerezM3fP8erLU5pFeXmjikq9qmR: {
    displaySymbol: "ENA",
    symbol: "ENA",
    type: "crypto",
    decimals: 8,
    decimals_gmx: 18,
    displayMarketName: "ENA/USD",
    isSynthetic: false,
  },
  HypeVcgZWXS1fSuij5R5Kp9JcYjw34ZG6yic1bde9vS5: {
    displaySymbol: "HYPE",
    symbol: "HYPE",
    type: "crypto",
    decimals: 9,
    decimals_gmx: 8,
    displayMarketName: "HYPE/USD",
    isSynthetic: false,
  },
  "9wX6Qz1Y5YQe71dfnFYFfZYXZhKqjYKQwdqfrRkmYUSX": {
    symbol: "WGMX",
    type: "crypto",
    displaySymbol: "GMX",
    decimals: 9,
    decimals_gmx: 18,
    displayMarketName: "GMX/USD",
    isSynthetic: true,
  },
  A7bdiYdS5GjqGFtxf17ppRHtDKPkkRqbKtR27dxvQXaS: {
    symbol: "ZEC",
    type: "crypto",
    displaySymbol: "ZEC",
    decimals: 8,
    decimals_gmx: 18,
    displayMarketName: "ZEC/USD",
    isSynthetic: true,
  },
  TaouYgVPRRT3TUkfTK7fQWkoSM35cbuMVEFAXifsuAf: {
    symbol: "TAO",
    type: "crypto",
    displaySymbol: "TAO",
    decimals: 8,
    decimals_gmx: 9,
    isSynthetic: false,
    displayMarketName: "TAO/USD",
  },
  Nearqg83ZH4Wbj2DDeN1EE86CUZaPFX2n8vErWNCPov: {
    symbol: "NEAR",
    type: "crypto",
    displaySymbol: "NEAR",
    decimals: 9,
    decimals_gmx: 24,
    isSynthetic: false,
    displayMarketName: "NEAR/USD",
  },
  EurdPiuWJazzqJLKE4Amb1ZQxVkpwEiSKCZfNgXC9Wi4: {
    symbol: "EUR",
    type: "forex",
    displaySymbol: "EURUSD",
    decimals: 9,
    decimals_gmx: 8,
    isSynthetic: false,
    displayMarketName: "EUR/USD",
  },
  GbpeVg2NBeL9Q2RDLrYkkkRXNMjaXg4vBZbh2cffH7aG: {
    symbol: "GBP",
    type: "forex",
    displaySymbol: "GBPUSD",
    decimals: 9,
    decimals_gmx: 8,
    isSynthetic: false,
    displayMarketName: "GBP/USD",
  },
  Audg5JLrnh6tRy6WWPRnZ1kh9xiWr2omtP5xdQRTvqQh: {
    symbol: "AUD",
    type: "forex",
    displaySymbol: "AUDUSD",
    decimals: 8,
    decimals_gmx: 8,
    isSynthetic: false,
    displayMarketName: "AUD/USD",
  },
  NzdGr62wT4t1xoHdYoVMEdWPb1yg9WQp2rQa34sscgJ: {
    symbol: "NZD",
    type: "forex",
    displaySymbol: "NZDUSD",
    decimals: 8,
    decimals_gmx: 8,
    isSynthetic: false,
    displayMarketName: "NZD/USD",
  },
  arb61K9FqhdBzLQdwi4aae6MLn94RzbcMs8varqwUt5: {
    symbol: "ARB",
    type: "crypto",
    displaySymbol: "ARB",
    decimals: 8,
    decimals_gmx: 18,
    isSynthetic: false,
    displayMarketName: "ARB/USD",
  },
  w1d1cTQ734BFeBdjUAHgH8tBk8EJ52PjcvroUq5Jekw: {
    displaySymbol: "WLD",
    symbol: "WLD",
    type: "crypto",
    decimals: 8,
    decimals_gmx: 18,
    displayMarketName: "WLD/USD",
    isSynthetic: false,
  },
  LitYCK3XFM7imaCwzutins43WCKfH8iubaEhp9JFPcj: {
    displaySymbol: "LIT",
    symbol: "LIT",
    type: "crypto",
    decimals: 8,
    decimals_gmx: 8,
    displayMarketName: "LIT/USD",
    isSynthetic: true,
  },
  VvvGPgHYN8KiC7H4aUQwJdfze5uB6rxkL63nHymxjZM: {
    displaySymbol: "VVV",
    symbol: "VVV",
    type: "crypto",
    decimals: 8,
    decimals_gmx: 8,
    displayMarketName: "VVV/USD",
    isSynthetic: true,
  },
  Xmric3gq5zb9bcuUW5o2MePQsnni3FxG2wavk6REm6X: {
    displaySymbol: "XMR",
    symbol: "XMR",
    type: "crypto",
    decimals: 8,
    decimals_gmx: 8,
    displayMarketName: "XMR/USD",
    isSynthetic: true,
  },
  ondoq3GfxTjnebAmpJ3mCLeoA2mZBRU8Kqoo6vTiaz1: {
    displaySymbol: "ONDO",
    symbol: "ONDO",
    type: "crypto",
    decimals: 8,
    decimals_gmx: 8,
    displayMarketName: "ONDO/USD",
    isSynthetic: true,
  },
  jpygxG9g45Lui4P3GQgfdfNSYcR9985HAcxBRPTHr66: {
    displaySymbol: "USDJPY",
    symbol: "USDJPY",
    type: "forex",
    decimals: 8,
    decimals_gmx: 8,
    displayMarketName: "USD/JPY",
    candleMarketName: "USDJPY/USD",
    isSynthetic: false,
  },
  cadDuN2bphC1u8K61ZF9hJCshTRmEyVNd4qiMY28ijo: {
    displaySymbol: "USDCAD",
    type: "forex",
    symbol: "USDCAD",
    decimals: 9,
    decimals_gmx: 8,
    displayMarketName: "USD/CAD",
    candleMarketName: "USDCAD/USD",
    isSynthetic: false,
  },
  chfdyavofe2ZXsU67oBnruALSgftfTntvDw3MvyEVRs: {
    displaySymbol: "USDCHF",
    symbol: "USDCHF",
    type: "forex",
    decimals: 8,
    decimals_gmx: 8,
    displayMarketName: "USD/CHF",
    candleMarketName: "USDCHF/USD",
    isSynthetic: false,
  },
  mxnZft9hb7nH93UxTApmXzk95Fg6BERE1PPRzwg6SLL: {
    displaySymbol: "USDMXN",
    symbol: "USDMXN",
    type: "forex",
    decimals: 8,
    decimals_gmx: 8,
    displayMarketName: "USD/MXN",
    candleMarketName: "USDMXN/USD",
    isSynthetic: false,
  },
  wtikDoxPLXGSBHacYcLf6SwLQEW5dqGKhErA73QeCrJ: {
    symbol: "WTI",
    type: "spot",
    displaySymbol: "WTI",
    decimals: 8,
    decimals_gmx: 8,
    displayMarketName: "WTI/USD",
    isSynthetic: true,
    tradingHours: "24/7",
  },
  xcu22Giuo4jqkDgv3KtfyUrco3a42BFLTnS7XjQ5Taz: {
    symbol: "XCU",
    type: "spot",
    displaySymbol: "XCU",
    decimals: 9,
    decimals_gmx: 9,
    displayMarketName: "XCU/USD",
    isSynthetic: true,
    tradingHours: "24/7",
  },
  xptah2VhwW4pcLdkMvUinEsDNvMXpgHiVfG2mmkEuGR: {
    symbol: "XPT",
    type: "spot",
    displaySymbol: "XPT",
    decimals: 8,
    decimals_gmx: 8,
    displayMarketName: "XPT/USD",
    isSynthetic: true,
    tradingHours: "24/7",
  },
  xpd2uvvfPfoogQxyrLyqE3NgSHSbkNNXr7bGnJWLB6n: {
    symbol: "XPD",
    type: "spot",
    displaySymbol: "XPD",
    decimals: 8,
    decimals_gmx: 8,
    displayMarketName: "XPD/USD",
    isSynthetic: true,
    tradingHours: "24/7",
  },
};

export function getSolanaTokenConfig(mint: string | undefined): SolanaTokenConfig | undefined {
  return mint ? GMX_SOLANA_TOKENS[mint] : undefined;
}
