import { Trans } from "@lingui/macro";

import { Faq, FaqItem } from "components/Faq/Faq";

const EARN_FAQ_ITEMS: FaqItem[] = [
  {
    title: <Trans>Where do GMX staking rewards come from?</Trans>,
    content: (
      <Trans>
        GMX staking rewards are generated through a 'buyback and distribute' process. GMX tokens are purchased on the
        open market using the revenue generated by the protocol. These tokens are then distributed back to stakers. No
        new GMX tokens are minted during this process.
      </Trans>
    ),
  },
  {
    title: <Trans>What's the difference between providing liquidity in GLV or GM?</Trans>,
    content: (
      <Trans>
        GLV and GM both enable liquidity provision on GMX, allowing users to earn fees from three revenue sources that
        auto-compound into the token's price. GM tokens represent liquidity in a single pool that supports one specific
        market on GMX. GLV vaults contain multiple GM tokens in an auto-rebalancing composition, thereby aggregating
        liquidity across various markets that have the same backing tokens (ex: ETH-USDC, or BTC-USDC). GM enables users
        to provide isolated liquidity with exposure to a specific market, while GLV allows users to passively earn yield
        from a diverse range of highly utilized pools.
      </Trans>
    ),
  },
  {
    title: <Trans>Can I unstake anytime?</Trans>,
    content: (
      <Trans>
        Yes, staking and providing liquidity are fully permissionless. The GMX, GLV, and GM tokens are liquid and can be
        unstaked and withdrawn at any time. For LP tokens, there could be some rare edge cases where your liquidity is
        being used for active trades. In that case, you can withdraw as soon as positions close.
      </Trans>
    ),
  },
  {
    title: <Trans>What networks are supported?</Trans>,
    content: (
      <Trans>
        Currently, staking GMX is only supported on Avalanche and Arbitrum. For providing liquidity, different GLV
        vaults and GM tokens are available on each blockchain. Please visit the Pools page for an overview of the
        liquidity products that are available on the chain you're connected to.
      </Trans>
    ),
  },
];

export default function EarnFaq() {
  return <Faq items={EARN_FAQ_ITEMS} title={<Trans>FAQ</Trans>} />;
}
