import { Trans } from "@lingui/macro";
import { useMemo } from "react";

import type { IncentivesConfig } from "domain/synthetics/incentives/v2/types";
import { formatFactorPercentage } from "domain/synthetics/incentives/v2/utils";

import { Faq, type FaqItem } from "components/Faq/Faq";

export function RewardsTiersFaq({ config }: { config: IncentivesConfig }) {
  const items: FaqItem[] = useMemo(
    () => [
      {
        title: <Trans>How does Rewards work?</Trans>,
        content: (
          <div className="flex flex-col gap-12">
            <div className="flex flex-col gap-4">
              <div className="font-medium text-typography-primary">
                <Trans>Trade & Stake to Earn Your Tiers</Trans>
              </div>
              <p>
                <Trans>
                  Trade and optionally stake GMX to increase your earning power. Your weekly trading volume sets your
                  volume tier, and the amount you stake sets your staking tier – together they form your reward
                  multiplier. The higher your tiers, the more you earn on your trading fees.
                </Trans>
              </p>
            </div>
            <div className="flex flex-col gap-4">
              <div className="font-medium text-typography-primary">
                <Trans>Receive Rewards</Trans>
              </div>
              <p>
                <Trans>
                  You receive {formatFactorPercentage(config.esGmxShareFactor)} of your rewards in esGMX, plus an
                  additional {formatFactorPercentage(config.gtShareFactor)} in GT tokens. esGMX can be vested into
                  liquid GMX over time. GT has not yet undergone its TGE, allowing holders to benefit from potential
                  token appreciation.
                </Trans>
              </p>
            </div>
          </div>
        ),
      },
      {
        title: <Trans>How are Rewards calculated?</Trans>,
        content: (
          <div className="flex flex-col gap-12">
            <p>
              <Trans>
                You earn esGMX and GT Rewards based on the fees paid each time you increase or decrease a position.
              </Trans>
            </p>
            <p>
              <Trans>Your Multiplier determines the amount of rewards you receive:</Trans>
            </p>
            <div>
              <div>
                <Trans>esGMX Rewards = Fees × (Multiplier × 10%)</Trans>
              </div>
              <div>
                <Trans>GT Rewards = 20% of esGMX Rewards</Trans>
              </div>
            </div>
            <p>
              <Trans>Rewards are distributed at the end of each epoch.</Trans>
            </p>
          </div>
        ),
      },
      {
        title: <Trans>How do multipliers work?</Trans>,
        content: (
          <div className="flex flex-col gap-12">
            <p>
              <Trans>
                Your Multiplier is calculated as the sum of your Volume Multiplier, Staking Multiplier, and any
                applicable Activity Boosts.
              </Trans>
            </p>
            <p>
              <Trans>The total Multiplier is capped at 10×.</Trans>
            </p>
          </div>
        ),
      },
      {
        title: <Trans>How long does a volume tier remain active?</Trans>,
        content: <Trans>A tier applies in the epoch it is achieved and remains active for 4 following epochs.</Trans>,
      },
      {
        title: <Trans>Are referral Rewards part of my multiplier?</Trans>,
        content: (
          <div className="flex flex-col gap-12">
            <p>
              <Trans>
                No. Referral rewards are added separately and are based on the trading volume generated by your
                referrals.
              </Trans>
            </p>
            <p>
              <Trans>You receive 50% of all rewards earned by the traders you invite.</Trans>
            </p>
          </div>
        ),
      },
      {
        title: <Trans>What is esGMX token?</Trans>,
        content: (
          <div className="flex flex-col gap-12">
            <p>
              <Trans>Escrowed GMX (esGMX) is a non-transferable token distributed as a reward.</Trans>
            </p>
            <p>
              <Trans>esGMX can be used in two ways:</Trans>
            </p>
            <div className="flex flex-col gap-4">
              <div className="font-medium text-typography-primary">
                <Trans>Vest it into liquid GMX</Trans>
              </div>
              <p>
                <Trans>
                  esGMX can be vested over a one-year period and converted into transferable GMX tokens. Vesting can be
                  managed from the Rewards page.
                </Trans>
              </p>
            </div>
            <div className="flex flex-col gap-4">
              <div className="font-medium text-typography-primary">
                <Trans>Stake it</Trans>
              </div>
              <p>
                <Trans>
                  Each staked esGMX token provides the same staking power as one staked GMX token. It earns staking
                  rewards and contributes toward your staking tier.
                </Trans>
              </p>
            </div>
          </div>
        ),
      },
      {
        title: <Trans>What is GT token?</Trans>,
        content: (
          <Trans>
            GT is the native token of GMTrade. It is currently distributed as a reward, while its broader utility is
            planned for a later stage of the platform’s development. Future GT use cases and benefits will be announced
            as they become available.
          </Trans>
        ),
      },
    ],
    [config]
  );

  return <Faq items={items} title={<Trans>FAQ</Trans>} />;
}
