#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

yarn test:ci &
PID1=$!

yarn test:ct &
PID2=$!

cd sdk && yarn test:ci &
PID3=$!

FAIL=0
wait $PID1 || FAIL=1
wait $PID2 || FAIL=1
wait $PID3 || FAIL=1
exit $FAIL
