import { parseTokens } from '@/utils/legacy/parse';
import { getGmw208Enabled, getGmw450Enabled } from '@/config/featureFlagEnable';
import { PublicKey } from '@solana/web3.js';
import { Tokens } from 'gmsol';
import { IS_DEVELOPMENT } from '@/config/env';
import {
  GLV_COMMODITY_TOKEN,
  GLV_FOREX_TOKEN,
  GLV_STOCK_TOKEN,
} from '@/utils/glv/glvTokens';

type ExtendedTokenConfig = Tokens[string] & {
  type?: 'crypto' | 'stock' | 'forex' | 'commodity' | 'spot';
  displaySymbol?: string;
  displayMarketName?: string;
  candleMarketName?: string;
  tradingHours?: '24/7';
  isNative?: boolean;
  isWrappedNative?: boolean
};

export const GMX_SOLANA_STORE_ADDRESS = new PublicKey(
  'CTDLvGGXnoxvqLyTpGzdGLg9pD6JexKxKXSV8tqqo8bN'
);
export const GMX_SOLANA_CONFIG_ADDRESS = new PublicKey(
  '55tVJJu5En1u4Vizh8yKbe9P6TtAx8BB6nqhFMQt4aB'
);
export const GMX_SOLANA_TREASURY_VAULT_CONFIG_ADDRESS = new PublicKey(
  '4tf9zEjvj2BUR9ZaAr53sQdULDWGGpJTr2zngSrmjtN6'
);

export const DEFAULT_MARKET_TOKENS = IS_DEVELOPMENT
  ? [
      '85UW4pE5L1QBCGg2vadJJk5JWQUc3iFNDE1xtrQqr2Vk',
      'C9MoDptpk6hS8izXiPvJnd6pFShBCRPSpb7FGfvdiboQ',
      '7VuNcy1A22rYfiaqaqbGZr9z9PmmahAsc6RNET165GiW',
      '338dwWNqFoXsaw8UzGjVnxqzvrfLWqtMTSUSeZXwaQnY',
      'B5ZqfnTzrG8odZxYMmBWfZbubAhSPaPcAF2JqT3g9vWC',
      '4pMNdMykwTwwU8qoR4awCsLEKSsm46QkXZAS51oZyuMf',
      'HrNo9f2sFss7hkriWMBUHr45fmqnjqa2aVTGTRRxbxqx',
      '5sdFW7wrKsxxYHMXoqDmNHkGyCWsbLEFb1x1gzBBm4Hx',
      'nkyxUp1fRzYwTNPZssugpAAR9UCHuLhJMkmXCYiqkh2',
      'HsvSQBLM1oG4Gy7gyBw4fB8yAXFSyCTprfhkgtk94LUZ',
      'DW5b4UTdehnn55imWMW1VDe1TzZ9W1PgDZahWa1XQwRx',
      'Ht4RdPf3bJYLUhJv2hTdZQ4WsoAuW44zyPGhiuqiJjnp',
      '4uRCqRuTPZTtr1nH6V1wYdX4nPg6Cs5agqj3iT7W7J64',
      '9ZTju81nuFZ3XZGShyJnnyh3mf9CQNmKNsjL7RnkDE9W',
      'xiLDzynfr7JEoYinAEunZtdz9ubjVAqa5Ap7gJ9y43L',
      '2zyCufMw25kyGypeZseSJZK3KNeYKHPYPzhZWukeUTsX',
      'CNRsEfxGA5sxNzeth43Bs7gjHqFpTfLe1F3GnWmVcWxh',
      GLV_STOCK_TOKEN,
      'CNRsEfxGA5sxNzeth43Bs7gjHqFpTfLe1F3GnWmVcWxh',
      '5vBmHGbDrPqJjLC87d8ZHmgt9YHximo5kEcBSnw3aKXs',
      'DCfNNYgxCxGUxg9ycQ8T5qHXmPDRt7qA81UGkLha4KWx',
      'CKJ3cTptiJpWHgtSTGYa9pk5SypvfUfVnxeip6ADrJK9',
      '3G5Pqk5d38tNKHb1gZX9qF8Mq25AuPtQU32V4LRAVHyL',
      '6YYKx97PBVNQMFqABh6RL7ycgAss6Nzzmis5Yq3R1yKz',
      'HCEitzjS88T4x3EpZ14EkrcawbhnZdev48a2nQfwAi37',
      'CN9QU95PsgDRZmbZZWBmKsZbzMhbd4548uKsJhiavsiu',
      'AyoGLirJeLkGnR5XtVWTmJE9z298KqHawDq33W8SJKYv',
      'GFUpBNnRceYLjoE5xY66AhrToxaGsiyZbkgPnTvLdwvW',
      '5eQ97WovkNDfxGoEXBBQhG1rCt11g9Uies96FTbjyi19',
    ]
  : [
      'DAY6Qr1FKgJQFvjJAhFUZUWHzx8UbbbkRmt6G6AYswWG',
      'AC7iz89CBopxsuzoPU5drW59PB9rZJYpvqaedGxAjFeK',
      '5q5x6DT4viJhTEtiFGkTRyDT9KDmYoGfZF3rERwjV8aV',
      'BvC73rarCMrhEnk3JmqaLntpnrwfUCR5eTrf7HQu6ieg',
      'Dqq58gS1TgRMDouUbdvhhzc51XXTNHG921WLxH9X2eB8',
      '6UU9sF5fryafHDYPcmVcV7ucfnYs6iMVcvb8p7SBQgTc',
      '9JMZj2F9EEMLoJTpftpxSHeixoPZXXkbJ9qLH5vhPXWT',
      '3pHXv5NsrxwkDdus2e1rTHoaNK9zUUnGwcwg1oeeCGzd',
      'CVYjDJknQnKUNFnuGrj75Lv6Pcm4AAencuYSZkQHQDtL',
      'xiLDzynfr7JEoYinAEunZtdz9ubjVAqa5Ap7gJ9y43L',
      'Eck19AsZP2sqGp4oAkrstTrgUmxjF6nQSQxiiHerweLg',
      'FvuQqxh9MJLDXD1FvDdv5X4HecoTEYHJA5558z8ptim4',
      'GErzt3fxfuQScQYtaKGGbgNtdk3LWDmKZ1YVZX2L4Tjc',
      'E6kfBQcdHL3fdWNaydrWViXVtQLTgpxzZicLy98ZNc5v',
      'J42dzcHkgmzU7MARv7k29TrkKaGQ1j2mTaYjkBkN7pn5',
      'FVUbre5BEnWKAN5ZxQ6MUgezS1X2ZUecq4HZDDsa1Q6i',
      'BjEpsvvjca1cQ6KGaeULn6sp8hPsP7XhRvUhepPX181c',
      '2MS6KM17L6JjQfAPfkzjezKre3xKsARdRQVjrdd6Kvmf',
      '527jUvh7guN8Fip96TeJhKWreeWdcwD9CFFwXG9mTiHQ',
      'BeyjceC5eXoq3pkmdoDHrE2UVwuYamAdXkM9GmphZFhE',
      'GX3bpUi5WyoJEjNjrLi3wPqV5xD9WcB1hEedLRSooi4H',
      'sWvE7CfFpES3WCbgeM45ZvAXRm34c9ssdf8PEApTqaX',
      '6dDEEisqtCL6Wh49gAHtXaoE9NkSKXHvLLuTqLPz9sDM',
      '2dVHXNgzC7vvcsDi89S6crSkX3Y6HzPgZfmWqttEzvmo',
      'EE889Nsvqkk3A82GXhxbCbpNkM6Fkqdgp8UNv5sZ2qU',
      '73mxoziw5uKnrXSAKA693b225r5aru1Sdkn9msXznh4R',
      'BwN2FWixP5JyKjJNyD1YcRKN1XhgvFtnzrPrkfyb4DkW',
      '2aGHXNEJAHmsiSVdz5h4stSjnLfohs79iSJdkDdZBs4F',
      '4QX94xP34zFJyeTxJQ4oJ4MeWcuRYViCDmxTjwAYN9Vp',
      '6kKGHF9tPoXvtyAGUY8mfuRCFXBw61xWfhfS4sSJbXFr',
      '5KSsaGZebQSAxZcYuzRz5JWCxoYztWYcfTcRBWLCwoMX',
      '2Ek8kU98XKeH4ErvQcEGoEf2Q2xqBMEK6bfjanypVeZP',
      '7RNev94wKusSmFEqo3gvv1d1zMweP6sa2LtjJjroAvym',
      '2wxH1sGLH4Rui6Ws4F1nFDHtW3aJDG1fAF3gZVJ7ktwV',
      '4x3BBE2tx8fFG2V6BjHEWevo3j3jraYWTAHVfKTt31w2',
      'AyCysi8mWtHWs7TLe13tFPCB515kSQHmBqkszpAeEqbK',
      'C1d1rAehpY5U79593gB7ne7V4CDErYgAcwpvjSMd3dok',
      '7X3EpLG2yW7SzPzz9NYarouQGMsPkYxZJBGEhVkkdXWW',
      '5bi8Ve65rhCjwP2ssmhwTQ7dtfRk5BSo6jYwtrJxkDQH',
      'D8VqUfw81UPnreceozYSHbmwdGizk9C4ekV6fXZqr6YJ',
      'EFdTdjGE6hze8RD4XjwmQJRd8CD9Soq3rbPm53dPcMsx',
      '5Sv9AETZBdR8JGpe3YMZJKzhvQmnLsAgcrfViJ8y8LB7',
      'FWw1tetkZETBz4iyToM7K1VhBMcnQQpHzqbHa1eqkdWe',
      '6udTz3TdPfKRZQ1GF1L372DkpFoFu4Hz2HSpyjdXrMVr',
      '6vUDkCZqCNF2dZnPRHDySDDYvvvVPQGM68qie4cYBQHL',
      'AxsNWzai8PPMBfVHFZxAZbn9wK24z86ozHkbbZCVtFDh',
      'DCfNNYgxCxGUxg9ycQ8T5qHXmPDRt7qA81UGkLha4KWx',
      '6LDgChGwztBmUAqqusSv4VnWeAzUrZvewTDvyAaMynD7',
      'GRT3cFnBkNNTs89wC9Q9qjU9JmZ6XTgu7fF4KRHgW5iR',
      'DWZHgZPGvvCTSAo1GrrEFsCwtRcxrU4BnTQokMMMN9Qe',
      '9vyRjXeJGKgikeQiqbVyL49tXwcMKFNnt5ig3TmsjyKT',
      'J3wiTkP3rfU23zJQX6sUU2z4iGAopC2kBxgGJMmMoY5M',
      'Gi1dxHsgnVLg1JQYqKDWsTfXD9U9GvhPJDg7Has266FL',
      '6KTCEqyMG9eErgSkfbe5QTc6eYnPcgJ4bKK63VZWqZWG',
      '5vBmHGbDrPqJjLC87d8ZHmgt9YHximo5kEcBSnw3aKXs',
      '9uQdTgDAvZgTwPYFGyzTaotAjSZcUKndwhLuzsQt1vto',
      '3oy9VYvMUh9iPRA4adCdGHJLPg2QUAqxupQZoaFR7vwV',
      '4GmYJA45W11rQYsWcq3CHvASY199wTQz2LFj8tQBqqWC',
      'BgiWpn6fEU3duXEyZN49kHwjxMdazkJi1aZrUQGQkWJn',
      'EVDVoXejNDFumTNos8C84nWRTUXPYJqCAdWfei7TwxZC',
      '6D5w1vz5yqLUTXsCpFBUPcZ5AnbHBsgG6XVGpc2ZcttK',
      'CH7pboF6PnCTAuWZbhC1eLKsX6rjd2UAPG87oqsizxR2',
      '6RXHXFAXmAkNkgk59b15ycEKxYrdEYB8Sv7WiyUT24vj',
      '2gYBsHNtxwj6Ydz159frrp7em7rT4KfEnk9a6AXDMyNV',
      '7p6syvfgMsUmCDjsX9wyBtXUk1zZoMH4WYquS83r1Scm',
      'F5EW8CrjYkksMvhm8nWBNY9HepUGLLqcXiq5tRftRPX2',
      'HCEitzjS88T4x3EpZ14EkrcawbhnZdev48a2nQfwAi37',
      'DLX3Aa17ebmyRp6Paxe16wn3QYtNVqdNH9AM9ZKLScfy',
      'FNCNNdBKjM2noAsEZsYbTRX2kXT1T4ig1CV2bjXTimAY',
      'C54H1AwSVGfFUFSwemcnzXTf6ZnWvDrHMnuqVMRXTH97',
      'EatSc7mNnGBa1VoSq867bZntWJFYFmj51u9X3tCLRLRb',
      '5PRmYd1WbEb1onzHAqaxevt6vAU2fCRSBeJBqSsMmkEh',
      'JA3xB9zFPBsWaAeDveLd3ia7maznJdL9qzLP81z5r73Z',
      '6WAqfHvHPixPNMUUUwK4ZiiUkQXe9X87smprTPR3rPqH',
      '5tNb3BpKoU3UsRs2NTmeHeYynyFhQ1bpiaoD5iCrLWSD',
      '996QqBhGoKfNike6G7aURTEoD7SX6CrJQw6DMnq354Nw',
      '3t88GTQgD1Dyi4qX1BeW1zpJ1d4g8wXieFeX5VXpCTNo',
      'HViSi2W1rwNYc5YtPynHADGLtitrmekpQGoGU561Zpoz',
      '4g6FhbTU5gYyqbFSudEsnZ7FgUAb5P9QAogJ6iVM6jYJ',
      'BXcGhms3ZnikNcEzU3ivKZJ8ia2Xn9jV1J6Kn8dUdUUH',
      'EERJDS82NSTazRF9jFdCGUTL6tBPg9FXe1yy7jvuS9V7',
      'CF5KBpj9C3ZP4UnRBaaMbKghCyFGoUDVqAVfxu1ikZho',
      '73LP1hqW5fphVvwX2HrwcHfLce1fLRvS1axH4GqVYNCp',
      '5yhCwf9pEbX1t6uevDEgQu2m8q8dPuXi9LUgpPJkTurV',
      'EgmB7CeymWucnEmVjpqKoXqTuZfMuxzPf89ZziU2gmPE',
      '5MpBQqsNFhuSJL27NAJ8W25TQ8yZVr6PZezjrU74LbMq',
      'A5wbRLowPh1T3CtD31KN25i6NqW7wk6Kc5fkED3qCLCn',
      '4X9uP7QX3zqjwQUWJhVznodUYA7RLGquhR2E8WeZeNBk',
      '31BzkcazjG25MZu9gbm5eezYb3b3ozEuQAvXdyftD7Q1',
    ];

const MARKET_TOKENS_FROM_ENV = import.meta.env.VITE_MARKET_TOKENS;
// eslint-disable-next-line @typescript-eslint/no-unsafe-assignment
const MARKET_TOKENS: string[] = MARKET_TOKENS_FROM_ENV
  ? JSON.parse(MARKET_TOKENS_FROM_ENV)
  : DEFAULT_MARKET_TOKENS;

  const NIGHTLY_MARKET_TOKENS: string[] = [
    ...['ZTn3eszWBDc96ryfYdmDZYd6cuaZ8WxfSCSG8GJnQ8d'], // WTI/USD
    ...(getGmw208Enabled()
      ? [
          'J2dWy224HDioMg5TMWd9jganuMGdiigs5YFZ6QkLVBew', // XCU/USD
          'DHtPBDyjAW82GGUV244gZR3TfMtFuYewwQ4qwpPFAsCP', // XPT/USD
          '94Mpdu745RWL2eBqu1SvuV2HnX9EfFQSGm3uxvfMBmv6', // XPD/USD
        ]
      : []),
  ];

export const GMX_SOLANA_MARKET_TOKENS = [...MARKET_TOKENS, ...NIGHTLY_MARKET_TOKENS].map(
  (pubkey) => new PublicKey(pubkey)
);

export const GMX_SOLANA_GLV_TOKENS = IS_DEVELOPMENT
  ? [
      new PublicKey('7r3XADNMW12k8QiLPaFjW1giYMJNZzUjmDA5HiK7hAPu'),
      new PublicKey('7uwzUKKbXHNmpC5x67apE7JgAmPoWWQpCf7jJZRTqjMk'),
      new PublicKey(GLV_STOCK_TOKEN),
      new PublicKey('HhVNkJ9EWi64j645aVfnNBqXguXvhvKHk7wRnS4wAYmz'),
    ]
  : [
      new PublicKey('7r3XADNMW12k8QiLPaFjW1giYMJNZzUjmDA5HiK7hAPu'),
      new PublicKey('7uwzUKKbXHNmpC5x67apE7JgAmPoWWQpCf7jJZRTqjMk'),
      new PublicKey(GLV_STOCK_TOKEN),
      new PublicKey('HhVNkJ9EWi64j645aVfnNBqXguXvhvKHk7wRnS4wAYmz'),
      new PublicKey(GLV_COMMODITY_TOKEN),
      new PublicKey(GLV_FOREX_TOKEN),
    ];
export const GMX_SOLANA_TOKENS_RAW: Record<string, ExtendedTokenConfig> = IS_DEVELOPMENT
  ? {
      '11111111111111111111111111111111': {
        symbol: 'SOL',
        type: 'crypto',
        displaySymbol: 'SOL',
        decimals: 9,
        decimals_gmx: 9,
        wrappedAddress: 'So11111111111111111111111111111111111111112',
        isNative: true,
        isSynthetic: true,
        displayMarketName: 'SOL/USD',
      },
      So1Zu7vPQQxrguzUehKAyVLpjcc769zxgBuDAsxTUMH: {
        symbol: 'SOL',
        type: 'crypto',
        displaySymbol: 'SOL',
        decimals: 9,
        decimals_gmx: 9,
        wrappedAddress: 'So11111111111111111111111111111111111111112',
        isNative: true,
        displayMarketName: 'SOL/USD',
      },
      So11111111111111111111111111111111111111112: {
        symbol: 'WSOL',
        type: 'crypto',
        displaySymbol: 'SOL',
        decimals: 9,
        decimals_gmx: 9,
        displayMarketName: 'SOL/USD',
      },
      UsdsBvJe6sPKBzZhEo9bDDVg6d3695gJonz9eVSAUpP: {
        symbol: 'USDC',
        type: 'crypto',
        displaySymbol: 'USDC',
        decimals: 6,
        decimals_gmx: 6,
        isStable: true,
        displayMarketName: 'USDC/USD',
      },
      wif68Xs36aEz4eVrpKvpUUdcfMn5mPPE9yHRXzX7NGA: {
        symbol: 'WIF',
        type: 'crypto',
        displaySymbol: 'WIF',
        decimals: 9,
        displayMarketName: 'WIF/USD',
        decimals_gmx: 6,
      },
      '1inkDh4FM7mvWQJ4s2xQReD34JWNpdiJqWxPcmsrBvS': {
        symbol: 'LINK',
        type: 'crypto',
        displaySymbol: 'LINK',
        decimals: 8,
        displayMarketName: 'LINK/USD',
        decimals_gmx: 18,
      },
      btc5UQ1DtJdCZg12ZCdznjrHB7xc957NQsfjZp4xZx1: {
        symbol: 'BTC',
        type: 'crypto',
        displaySymbol: 'BTC',
        decimals: 8,
        displayMarketName: 'BTC/USD',
        decimals_gmx: 8,
      },
      ethGTfH3DPUn8nSmUdfgdJHqJJyT41rRM2tjibFUSoG: {
        symbol: 'ETH',
        type: 'crypto',
        displaySymbol: 'ETH',
        decimals: 8,
        displayMarketName: 'ETH/USD',
        decimals_gmx: 18,
      },
      bome449XB96C7J7u9HorwqUyh4qAyS4XjbpqNreTmYW: {
        symbol: 'BOME',
        type: 'crypto',
        displaySymbol: 'BOME',
        decimals: 9,
        displayMarketName: 'BOME/USD',
        decimals_gmx: 6,
      },
      bonkpQke5XvuDfTwRAGv2LtDyB2Lsq41WNXpCZXZWVy: {
        symbol: 'BONK',
        type: 'crypto',
        displaySymbol: 'BONK',
        decimals: 5,
        displayMarketName: 'BONK/USD',
        decimals_gmx: 5,
      },
      gmxNA9d2BkpQZ6xz2Cpm3si7cp6X5iAf9NxN1gwWtQW: {
        symbol: 'GMX',
        type: 'crypto',
        displaySymbol: 'GMX',
        decimals: 8,
        displayMarketName: 'GMX/USD',
        decimals_gmx: 18,
      },
      me1avw1nR4F8TaJQfPZpAd5F9tBSAmooCxGdCXB3Vem: {
        symbol: 'MELANIA',
        type: 'crypto',
        displaySymbol: 'MELANIA',
        decimals: 6,
        displayMarketName: 'MELANIA/USD',
        decimals_gmx: 6,
      },
      truMYnGqJqX3Be9LKqqBm218AsauUPcwW7QCgDSyPkF: {
        displaySymbol: 'TRUMP',
        symbol: 'TRUMP',
        type: 'crypto',
        decimals: 6,
        displayMarketName: 'TRUMP/USD',
        decimals_gmx: 6,
      },
      Spy8ZriFq6b5rj1Xeypp5vVLkmdEiQfQqsxbjycoYPN: {
        symbol: 'SPY',
        type: 'stock',
        decimals: 8,
        displayMarketName: 'SPY/USD',
        decimals_gmx: 8,
        isSynthetic: true,
      },
      Msftix9DNgRjxF7SXjjqfxjusmaXByNnDc6cdX3Z2qu: {
        symbol: 'MSFT',
        type: 'stock',
        displaySymbol: 'MSFT',
        displayMarketName: 'MSFT/USD',
        decimals: 8,
        decimals_gmx: 8,
        isSynthetic: true,
      },
      Ts1F5Xa8WR4mGqpZ35bhDM56MHf7Zzvq3L6dYGXVdk4: {
        symbol: 'TSLA',
        type: 'stock',
        displaySymbol: 'TSLA',
        decimals: 8,
        decimals_gmx: 8,
        isSynthetic: true,
        displayMarketName: 'TSLA/USD',
      },
      BnbZiefu5Ffn1QWsZvvNuvppvMs9MEzj2rBDCJQzGmBe: {
        displaySymbol: 'BNB',
        symbol: 'BNB',
        type: 'crypto',
        decimals: 9,
        decimals_gmx: 18,
        displayMarketName: 'BNB/USD',
        isSynthetic: true,
      },
      XaurYjNVXW8w61bXjWHGLJbGjcDhRhGDUwS1hEoLCp7: {
        symbol: 'XAU',
        type: 'spot' as const,
        displaySymbol: 'XAU',
        decimals: 8,
        decimals_gmx: 8,
        displayMarketName: 'XAU/USD',
        isSynthetic: true,
        tradingHours: '24/7' as const,
      },
      Wtipz9V5BMqzuvt4JM4yn4tfcqNFwApbcVnBVfL5bxg: {
        symbol: 'WTI',
        type: 'spot' as const,
        displaySymbol: 'WTI',
        decimals: 8,
        decimals_gmx: 8,
        displayMarketName: 'WTI/USD',
        isSynthetic: true,
        tradingHours: '24/7' as const,
      },
      BrtjQJGj7QvRnCur56ng2F3hL52JL5euavgvf5VqJMTZ: {
        symbol: 'BRENT',
        type: 'spot' as const,
        displaySymbol: 'BRENT',
        decimals: 8,
        decimals_gmx: 8,
        displayMarketName: 'BRENT/USD',
        isSynthetic: true,
        tradingHours: '24/7' as const,
      },
      Eurzo3GcsjD9sf32gC4RUu8oUVVmFV2oWqCZvfnzshXM: {
        symbol: 'EUR',
        type: 'forex' as const,
        displaySymbol: 'EURUSD',
        decimals: 8,
        decimals_gmx: 8,
        displayMarketName: 'EUR/USD',
        isSynthetic: true,
        tradingHours: '24/7' as const,
      },
    }
  : {
      // not dev
      '11111111111111111111111111111111': {
        symbol: 'SOL',
        type: 'crypto',
        displaySymbol: 'SOL',
        decimals: 9,
        decimals_gmx: 9,
        wrappedAddress: 'So11111111111111111111111111111111111111112',
        isNative: true,
        isSynthetic: true,
        displayMarketName: 'SOL/USD',
      },
      So1Zu7vPQQxrguzUehKAyVLpjcc769zxgBuDAsxTUMH: {
        symbol: 'SOL',
        type: 'crypto',
        displaySymbol: 'SOL',
        decimals: 9,
        decimals_gmx: 9,
        wrappedAddress: 'So11111111111111111111111111111111111111112',
        isNative: true,
        displayMarketName: 'SOL/USD',
      },
      So11111111111111111111111111111111111111112: {
        symbol: 'WSOL',
        type: 'crypto',
        displaySymbol: 'SOL',
        decimals: 9,
        decimals_gmx: 9,
        isWrappedNative: true,
        displayMarketName: 'SOL/USD',
      },
      EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v: {
        symbol: 'USDC',
        type: 'crypto',
        displaySymbol: 'USDC',
        decimals: 6,
        decimals_gmx: 6,
        isStable: true,
        displayMarketName: 'USDC/USD',
      },
      Es9vMFrzaCERmJfrF4H2FYD4KCoNkY11McCe8BenwNYB: {
        symbol: 'USDT',
        type: 'crypto',
        displaySymbol: 'USDT',
        decimals: 6,
        decimals_gmx: 6,
        isStable: true,
        displayMarketName: 'USDT/USD',
      },
      EKpQGSJtjMFqKZ9KQanSqYXRcF8fBopzLHYxdM65zcjm: {
        symbol: 'WIF',
        type: 'crypto',
        displaySymbol: 'WIF',
        decimals: 6,
        decimals_gmx: 6,
        displayMarketName: 'WIF/USD',
      },
      '2wpTofQ8SkACrkZWrZDjXPitYa8AwWgX8AfxdeBRRVLX': {
        symbol: 'LINK',
        type: 'crypto',
        displaySymbol: 'LINK',
        decimals: 8,
        decimals_gmx: 18,
        displayMarketName: 'LINK/USD',
      },
      BtcTQYRj7HRRk7MwnWiTFj8rWqN2ALt2QYig4cSWqTbv: {
        symbol: 'BTC',
        type: 'crypto',
        displaySymbol: 'BTC',
        decimals: 8,
        decimals_gmx: 8,
        displayMarketName: 'BTC/USD',
        isSynthetic: true,
      },
      '3NZ9JMVBmGAqocybic2c7LQCJScmgsAZ6vQqTDzcqmJh': {
        symbol: 'WBTC',
        type: 'crypto',
        displaySymbol: 'WBTC',
        decimals: 8,
        decimals_gmx: 8,
        displayMarketName: 'BTC/USD',
      },
      EthK4kKnQQUd1Ae1w7sdiMAUaJwq2RMwr7AtscXEdEsF: {
        symbol: 'ETH',
        type: 'crypto',
        displaySymbol: 'ETH',
        decimals: 8,
        decimals_gmx: 18,
        displayMarketName: 'ETH/USD',
        isSynthetic: true,
      },
      '7vfCXTUXx5WJV5JADk17DUJ4ksgau7utNKj4b963voxs': {
        symbol: 'WETH',
        type: 'crypto',
        displaySymbol: 'WETH',
        decimals: 8,
        decimals_gmx: 18,
        displayMarketName: 'ETH/USD',
      },
      ukHH6c7mMyiWCf1b9pnWe25TSpkDDt3H5pQZgZ74J82: {
        symbol: 'BOME',
        type: 'crypto',
        displaySymbol: 'BOME',
        decimals: 6,
        decimals_gmx: 6,
        displayMarketName: 'BOME/USD',
      },
      DezXAZ8z7PnrnRJjz3wXBoRgixCa6xjnB7YaB1pPB263: {
        symbol: 'BONK',
        type: 'crypto',
        displaySymbol: 'BONK',
        decimals: 5,
        decimals_gmx: 5,
        displayMarketName: 'BONK/USD',
      },
      FUAfBo2jgks6gB4Z4LfZkqSZgzNucisEHqnNebaRxM1P: {
        symbol: 'MELANIA',
        type: 'crypto',
        displaySymbol: 'MELANIA',
        decimals: 6,
        decimals_gmx: 6,
        displayMarketName: 'MELANIA/USD',
      },
      '6p6xgHyF7AeE6TZkSmFsko444wqoP15icUSqi2jfGiPN': {
        symbol: 'TRUMP',
        type: 'crypto',
        displaySymbol: 'TRUMP',
        decimals: 6,
        decimals_gmx: 6,
        displayMarketName: 'TRUMP/USD',
      },
      '9BB6NFEcjBCtnNLFko2FqVQBq8HHM13kCyYcdQbgpump': {
        symbol: 'FARTCOIN',
        type: 'crypto',
        displaySymbol: 'FARTCOIN',
        decimals: 6,
        decimals_gmx: 6,
        displayMarketName: 'FARTCOIN/USD',
      },
      GmxDsqjKYUrwgbvccGrpF1LoyHPUq8FQqT1FJfkvrMfY: {
        symbol: 'GMX',
        type: 'crypto',
        displaySymbol: 'GMX',
        decimals: 9,
        decimals_gmx: 18,
        isSynthetic: true,
        displayMarketName: 'GMX/USD',
      },
      DogeJP1vR955QsXWKT1vw5gJsyiTthqPEtJZj8enDWxF: {
        symbol: 'DOGE',
        type: 'crypto',
        displaySymbol: 'DOGE',
        decimals: 8,
        decimals_gmx: 8,
        isSynthetic: true,
        displayMarketName: 'DOGE/USD',
      },
      LtcsFqdfsLyoHZ7cRt9BkijqbFRAN1M4fB8naGaykTF: {
        symbol: 'LTC',
        type: 'crypto',
        displaySymbol: 'LTC',
        decimals: 8,
        decimals_gmx: 8,
        isSynthetic: true,
        displayMarketName: 'LTC/USD',
      },
      Unicsoj67GbDzQyWXQEh9vG5jBiVhMREtWBVDAFVpQq: {
        symbol: 'UNI',
        type: 'crypto',
        displaySymbol: 'UNI',
        decimals: 8,
        decimals_gmx: 18,
        isSynthetic: true,
        displayMarketName: 'UNI/USD',
      },
      XrpSaeAcbKAGv8P3kWbMbwbq8xcWgR548yvyiKKJUB9: {
        symbol: 'XRP',
        type: 'crypto',
        displaySymbol: 'XRP',
        decimals: 6,
        decimals_gmx: 6,
        isSynthetic: true,
        displayMarketName: 'XRP/USD',
      },
      BnbuyeSZgnWxXppzkRgiA5TR4t3L9NBRnk6Hbr9m5GsJ: {
        symbol: 'BNB',
        type: 'crypto',
        displaySymbol: 'BNB',
        decimals: 8,
        decimals_gmx: 18,
        isSynthetic: true,
        displayMarketName: 'BNB/USD',
      },
      AaveaPPwFJx88apsgcpzck7xkohpiZPViKkNndRZJ6pv: {
        symbol: 'AAVE',
        type: 'crypto',
        displaySymbol: 'AAVE',
        decimals: 8,
        decimals_gmx: 18,
        isSynthetic: true,
        displayMarketName: 'AAVE/USD',
      },
      PepeCS5SuDLkUwfnhmBLsPsVdpy9WR5bmXT4dkipR9i: {
        symbol: 'PEPE',
        type: 'crypto',
        displaySymbol: 'PEPE',
        decimals: 5,
        decimals_gmx: 18,
        isSynthetic: true,
        displayMarketName: 'PEPE/USD',
      },
      SuiyRuzKdsxGgdhVJGg5dDz6wtNSQUAWN21zSdCmYXs: {
        symbol: 'SUI',
        type: 'crypto',
        displaySymbol: 'SUI',
        decimals: 9,
        decimals_gmx: 9,
        isSynthetic: true,
        displayMarketName: 'SUI/USD',
      },
      BchGdYptcKvUDCpHMDAB5h1MfXq2LPzRLcU8b4r8dQiQ: {
        symbol: 'BCH',
        type: 'crypto',
        displaySymbol: 'BCH',
        decimals: 8,
        decimals_gmx: 8,
        isSynthetic: true,
        displayMarketName: 'BCH/USD',
      },
      TonDqfXQT4A9oexj8nWdQuUs97Zep5UG5auXByTKe79: {
        symbol: 'TON',
        type: 'crypto',
        displaySymbol: 'TON',
        decimals: 9,
        decimals_gmx: 9,
        isSynthetic: true,
        displayMarketName: 'TON/USD',
      },
      KgV1GvrHQmRBY8sHQQeUKwTm2r2h8t4C8qt12Cw1HVE: {
        symbol: 'AVAX',
        type: 'crypto',
        displaySymbol: 'AVAX',
        decimals: 8,
        decimals_gmx: 18,
        isSynthetic: true,
        displayMarketName: 'AVAX/USD',
      },
      TrxYuLyf3WbYPrQ84cjyWgfcEeKTc7m5cKBNBZhY5MN: {
        symbol: 'TRX',
        type: 'crypto',
        displaySymbol: 'TRX',
        decimals: 8,
        decimals_gmx: 6,
        isSynthetic: true,
        displayMarketName: 'TRX/USD',
      },
      X1mpyVGnE5VhzwbAqLp1FuAW7oY45WPTDisbcEkbVLq: {
        symbol: 'XLM',
        type: 'crypto',
        displaySymbol: 'XLM',
        decimals: 8,
        decimals_gmx: 7,
        isSynthetic: true,
        displayMarketName: 'XLM/USD',
      },
      AdamfezT5MsUMv5PtSBDWHwPCpcYVyq2CWAseqNbwU7Q: {
        symbol: 'ADA',
        type: 'crypto',
        displaySymbol: 'ADA',
        decimals: 8,
        decimals_gmx: 6,
        isSynthetic: true,
        displayMarketName: 'ADA/USD',
      },
      DotB5VDVP2VbfETfRsEsWnPH42tBiQZxHjGNH4iaNGSR: {
        symbol: 'DOT',
        type: 'crypto',
        displaySymbol: 'DOT',
        decimals: 8,
        decimals_gmx: 10,
        isSynthetic: true,
        displayMarketName: 'DOT/USD',
      },
      ShibkCetJam99AeDv93Q4KKVkeLCBSLSmBKNLpwt1ik: {
        symbol: 'SHIB',
        type: 'crypto',
        displaySymbol: 'SHIB',
        decimals: 6,
        decimals_gmx: 18,
        isSynthetic: true,
        displayMarketName: 'SHIB/USD',
      },
      pumpCmXqMfrsAkQ5r49WcJnRayYRqmXz6ae8H7H9Dfn: {
        symbol: 'PUMP',
        type: 'crypto',
        displaySymbol: 'PUMP',
        decimals: 6,
        decimals_gmx: 18,
        isSpl2022Mint: true,
        shouldWrap: true,
        wrappedAddress: 'HTHR6CbWSqrVCB83onNwKKH1W3qpGoKbpqvs9sgK7PEC',
        displayMarketName: 'PUMP/USD',
      },
      HTHR6CbWSqrVCB83onNwKKH1W3qpGoKbpqvs9sgK7PEC: {
        symbol: 'WPUMP',
        type: 'crypto',
        displaySymbol: 'WPUMP',
        decimals: 6,
        decimals_gmx: 18,
        displayMarketName: 'PUMP/USD',
      },
      SpyoXYfv2RmbLkURbxyXvxs83PFFNMiirXgZhBAgxBQ: {
        symbol: 'SPY',
        type: 'stock',
        displaySymbol: 'SPY',
        decimals: 8,
        decimals_gmx: 8,
        isSynthetic: true,
        displayMarketName: 'SPY/USD',
      },
      Msftix9DNgRjxF7SXjjqfxjusmaXByNnDc6cdX3Z2qu: {
        symbol: 'MSFT',
        type: 'stock',
        displaySymbol: 'MSFT',
        decimals: 8,
        decimals_gmx: 8,
        isSynthetic: true,
        displayMarketName: 'MSFT/USD',
      },
      AapaFKgsAsCMqSvXBPXqipX5WWxArgnPbADSNfhU9E9J: {
        symbol: 'AAPL',
        type: 'stock',
        displaySymbol: 'AAPL',
        decimals: 8,
        decimals_gmx: 8,
        isSynthetic: true,
        displayMarketName: 'AAPL/USD',
      },
      AmzF1ANXKgmWzm8TLmjAUaZTeqT4gZGV9Xi81yLx1FF9: {
        symbol: 'AMZN',
        type: 'stock',
        displaySymbol: 'AMZN',
        decimals: 8,
        decimals_gmx: 8,
        isSynthetic: true,
        displayMarketName: 'AMZN/USD',
      },
      GooBXeDfVwNPMCvHvGvUtEVxt1GwGzXxL8kqv8YKsAAy: {
        symbol: 'GOOGL',
        type: 'stock',
        displaySymbol: 'GOOGL',
        decimals: 8,
        decimals_gmx: 8,
        isSynthetic: true,
        displayMarketName: 'GOOGL/USD',
      },
      Metn9UEcTz2oUDL2rBmxrvTvhL2TfYBqvfYnjf1xptt: {
        symbol: 'META',
        type: 'stock',
        displaySymbol: 'META',
        decimals: 8,
        decimals_gmx: 8,
        isSynthetic: true,
        displayMarketName: 'META/USD',
      },
      Mst8Wf1EzeQi9pmtuhRoJ85DG7EPzBoa38bayRvNZXb: {
        displaySymbol: 'MSTR',
        symbol: 'MSTR',
        type: 'stock',
        decimals: 8,
        decimals_gmx: 8,
        isSynthetic: true,
        displayMarketName: 'MSTR/USD',
      },
      NvdwZ2PeA9HaCnRu59ZmRXGQJfyaRVTVZuxZ79voGWP: {
        symbol: 'NVDA',
        type: 'stock',
        displaySymbol: 'NVDA',
        decimals: 8,
        decimals_gmx: 8,
        isSynthetic: true,
        displayMarketName: 'NVDA/USD',
      },
      QqqSrHycWaS3f3o4fvEgeVfXfZbqdchUGB3rGxok9qj: {
        symbol: 'QQQ',
        type: 'stock',
        displaySymbol: 'QQQ',
        decimals: 8,
        decimals_gmx: 8,
        isSynthetic: true,
        displayMarketName: 'QQQ/USD',
      },
      Spc8vPRaUMi4KKofgM8duFQRBK58xjS15pdzgioAAhD: {
        symbol: 'SPCX',
        type: 'stock',
        displaySymbol: 'SPCX',
        decimals: 8,
        decimals_gmx: 8,
        isSynthetic: true,
        displayMarketName: 'SPCX/USD',
      },
      Ts1F5Xa8WR4mGqpZ35bhDM56MHf7Zzvq3L6dYGXVdk4: {
        symbol: 'TSLA',
        type: 'stock',
        displaySymbol: 'TSLA',
        decimals: 8,
        decimals_gmx: 8,
        displayMarketName: 'TSLA/USD',
        isSynthetic: true,
      },
      XagEFqWzJtB3XezX6KLQtGkBQDdTpcXYDG7X3EdMH2Y: {
        symbol: 'XAG',
        type: 'spot',
        displaySymbol: 'XAG',
        decimals: 8,
        decimals_gmx: 8,
        displayMarketName: 'XAG/USD',
        isSynthetic: true,
        tradingHours: '24/7',
      },
      Xauxf2VJhbue14FGbp3W8XwfQSECHYpiPMNMWSCwjSR: {
        symbol: 'XAU',
        type: 'spot',
        displaySymbol: 'XAU',
        decimals: 8,
        decimals_gmx: 8,
        displayMarketName: 'XAU/USD',
        isSynthetic: true,
        tradingHours: '24/7',
      },
      WLFinEv6ypjkczcS83FZqFpgFZYwQXutRbxGe7oC16g: {
        symbol: 'WLFI',
        type: 'crypto',
        displaySymbol: 'WLFI',
        decimals: 6,
        decimals_gmx: 18,
        displayMarketName: 'WLFI/USD',
        isSynthetic: false,
      },
      C1MHyoTJpRTeS9AQCyspNVu2EWAYCZwmJ1jNkEArFP1f: {
        symbol: 'APE',
        type: 'crypto',
        displaySymbol: 'APE',
        decimals: 9,
        decimals_gmx: 18,
        displayMarketName: 'APE/USD',
        isSynthetic: false,
      },
      Xp1adJXBj9MhK7hwAbgPN2rhuiK64nfMYTSg9vzgUB2: {
        displaySymbol: 'XPL',
        symbol: 'XPL',
        type: 'crypto',
        decimals: 8,
        decimals_gmx: 18,
        displayMarketName: 'XPL/USD',
        isSynthetic: false,
      },
      Ast9jCRDBog1oWQUJbhXbGhiPcjPTgsbPKf3qGK8vixc: {
        displaySymbol: 'ASTER',
        symbol: 'ASTER',
        type: 'crypto',
        decimals: 8,
        decimals_gmx: 18,
        displayMarketName: 'ASTER/USD',
        isSynthetic: false,
      },
      EnaRUVoWPozu58p8FerezM3fP8erLU5pFeXmjikq9qmR: {
        displaySymbol: 'ENA',
        symbol: 'ENA',
        type: 'crypto',
        decimals: 8,
        decimals_gmx: 18,
        displayMarketName: 'ENA/USD',
        isSynthetic: false,
      },
      HypeVcgZWXS1fSuij5R5Kp9JcYjw34ZG6yic1bde9vS5: {
        displaySymbol: 'HYPE',
        symbol: 'HYPE',
        type: 'crypto',
        decimals: 9,
        decimals_gmx: 8,
        displayMarketName: 'HYPE/USD',
        isSynthetic: false,
      },
      '9wX6Qz1Y5YQe71dfnFYFfZYXZhKqjYKQwdqfrRkmYUSX': {
        symbol: 'WGMX',
        type: 'crypto',
        displaySymbol: 'GMX',
        decimals: 9,
        decimals_gmx: 18,
        displayMarketName: 'GMX/USD',
        isSynthetic: true,
      },
      A7bdiYdS5GjqGFtxf17ppRHtDKPkkRqbKtR27dxvQXaS: {
        symbol: 'ZEC',
        type: 'crypto',
        displaySymbol: 'ZEC',
        decimals: 8,
        decimals_gmx: 18,
        displayMarketName: 'ZEC/USD',
        isSynthetic: true,
      },
      TaouYgVPRRT3TUkfTK7fQWkoSM35cbuMVEFAXifsuAf: {
        symbol: 'TAO',
        type: 'crypto',
        displaySymbol: 'TAO',
        decimals: 8,
        decimals_gmx: 9,
        isSynthetic: false,
        displayMarketName: 'TAO/USD',
      },
      Nearqg83ZH4Wbj2DDeN1EE86CUZaPFX2n8vErWNCPov: {
        symbol: 'NEAR',
        type: 'crypto',
        displaySymbol: 'NEAR',
        decimals: 9,
        decimals_gmx: 24,
        isSynthetic: false,
        displayMarketName: 'NEAR/USD',
      },
      EurdPiuWJazzqJLKE4Amb1ZQxVkpwEiSKCZfNgXC9Wi4: {
        symbol: 'EUR',
        type: 'forex',
        displaySymbol: 'EURUSD',
        decimals: 9,
        decimals_gmx: 8,
        isSynthetic: false,
        displayMarketName: 'EUR/USD',
      },
      GbpeVg2NBeL9Q2RDLrYkkkRXNMjaXg4vBZbh2cffH7aG: {
        symbol: 'GBP',
        type: 'forex',
        displaySymbol: 'GBPUSD',
        decimals: 9,
        decimals_gmx: 8,
        isSynthetic: false,
        displayMarketName: 'GBP/USD',
      },
      Audg5JLrnh6tRy6WWPRnZ1kh9xiWr2omtP5xdQRTvqQh: {
        symbol: 'AUD',
        type: 'forex',
        displaySymbol: 'AUDUSD',
        decimals: 8,
        decimals_gmx: 8,
        isSynthetic: false,
        displayMarketName: 'AUD/USD',
      },
      NzdGr62wT4t1xoHdYoVMEdWPb1yg9WQp2rQa34sscgJ: {
        symbol: 'NZD',
        type: 'forex',
        displaySymbol: 'NZDUSD',
        decimals: 8,
        decimals_gmx: 8,
        isSynthetic: false,
        displayMarketName: 'NZD/USD',
      },
      arb61K9FqhdBzLQdwi4aae6MLn94RzbcMs8varqwUt5: {
        symbol: 'ARB',
        type: 'crypto',
        displaySymbol: 'ARB',
        decimals: 8,
        decimals_gmx: 18,
        isSynthetic: false,
        displayMarketName: 'ARB/USD',
      },
      w1d1cTQ734BFeBdjUAHgH8tBk8EJ52PjcvroUq5Jekw: {
        displaySymbol: 'WLD',
        symbol: 'WLD',
        type: 'crypto',
        decimals: 8,
        decimals_gmx: 18,
        displayMarketName: 'WLD/USD',
        isSynthetic: false,
      },
      LitYCK3XFM7imaCwzutins43WCKfH8iubaEhp9JFPcj: {
        displaySymbol: 'LIT',
        symbol: 'LIT',
        type: 'crypto',
        decimals: 8,
        decimals_gmx: 8,
        displayMarketName: 'LIT/USD',
        isSynthetic: true,
      },
      VvvGPgHYN8KiC7H4aUQwJdfze5uB6rxkL63nHymxjZM: {
        displaySymbol: 'VVV',
        symbol: 'VVV',
        type: 'crypto',
        decimals: 8,
        decimals_gmx: 8,
        displayMarketName: 'VVV/USD',
        isSynthetic: true,
      },
      Xmric3gq5zb9bcuUW5o2MePQsnni3FxG2wavk6REm6X: {
        displaySymbol: 'XMR',
        symbol: 'XMR',
        type: 'crypto',
        decimals: 8,
        decimals_gmx: 8,
        displayMarketName: 'XMR/USD',
        isSynthetic: true,
      },
      ondoq3GfxTjnebAmpJ3mCLeoA2mZBRU8Kqoo6vTiaz1: {
        displaySymbol: 'ONDO',
        symbol: 'ONDO',
        type: 'crypto',
        decimals: 8,
        decimals_gmx: 8,
        displayMarketName: 'ONDO/USD',
        isSynthetic: true,
      },
      jpygxG9g45Lui4P3GQgfdfNSYcR9985HAcxBRPTHr66: {
        displaySymbol: 'USDJPY',
        symbol: 'USDJPY',
        type: 'forex',
        decimals: 8,
        decimals_gmx: 8,
        displayMarketName: 'USD/JPY',
        candleMarketName: 'USDJPY/USD',
        isSynthetic: false,
      },
      cadDuN2bphC1u8K61ZF9hJCshTRmEyVNd4qiMY28ijo: {
        displaySymbol: 'USDCAD',
        type: 'forex',
        symbol: 'USDCAD',
        decimals: 9,
        decimals_gmx: 8,
        displayMarketName: 'USD/CAD',
        candleMarketName: 'USDCAD/USD',
        isSynthetic: false,
      },
      chfdyavofe2ZXsU67oBnruALSgftfTntvDw3MvyEVRs: {
        displaySymbol: 'USDCHF',
        symbol: 'USDCHF',
        type: 'forex',
        decimals: 8,
        decimals_gmx: 8,
        displayMarketName: 'USD/CHF',
        candleMarketName: 'USDCHF/USD',
        isSynthetic: false,
      },
      mxnZft9hb7nH93UxTApmXzk95Fg6BERE1PPRzwg6SLL: {
        displaySymbol: 'USDMXN',
        symbol: 'USDMXN',
        type: 'forex',
        decimals: 8,
        decimals_gmx: 8,
        displayMarketName: 'USD/MXN',
        candleMarketName: 'USDMXN/USD',
        isSynthetic: false,
      },
      wtikDoxPLXGSBHacYcLf6SwLQEW5dqGKhErA73QeCrJ: {
        symbol: 'WTI',
        type: 'spot' as const,
        displaySymbol: 'WTI',
        decimals: 8,
        decimals_gmx: 8,
        displayMarketName: 'WTI/USD',
        isSynthetic: true,
        tradingHours: '24/7',
      },
      ...(getGmw208Enabled()
        ? {
            xcu22Giuo4jqkDgv3KtfyUrco3a42BFLTnS7XjQ5Taz: {
              symbol: 'XCU',
              type: 'spot' as const,
              displaySymbol: 'XCU',
              decimals: 9,
              decimals_gmx: 9,
              displayMarketName: 'XCU/USD',
              isSynthetic: true,
              ...(getGmw450Enabled() ? { tradingHours: '24/7' as const } : {}),
            },
            xptah2VhwW4pcLdkMvUinEsDNvMXpgHiVfG2mmkEuGR: {
              symbol: 'XPT',
              type: 'spot' as const,
              displaySymbol: 'XPT',
              decimals: 8,
              decimals_gmx: 8,
              displayMarketName: 'XPT/USD',
              isSynthetic: true,
              tradingHours: '24/7',
            },
            xpd2uvvfPfoogQxyrLyqE3NgSHSbkNNXr7bGnJWLB6n: {
              symbol: 'XPD',
              type: 'spot' as const,
              displaySymbol: 'XPD',
              decimals: 8,
              decimals_gmx: 8,
              displayMarketName: 'XPD/USD',
              isSynthetic: true,
              tradingHours: '24/7',
            },
          }
        : {}),
    };

export function isAlwaysOpenTokenBySymbol(symbol: string): boolean {
  const upperSymbol = symbol.toUpperCase();
  return Object.values(GMX_SOLANA_TOKENS_RAW).some(
    (config) =>
      config.symbol.toUpperCase() === upperSymbol &&
      config.tradingHours === '24/7'
  );
}

const TOKENS_FROM_ENV = import.meta.env.VITE_TOKENS;
// eslint-disable-next-line @typescript-eslint/no-unsafe-assignment
const TOKENS: Tokens = TOKENS_FROM_ENV
  ? JSON.parse(TOKENS_FROM_ENV)
  : GMX_SOLANA_TOKENS_RAW;
export const GMX_SOLANA_TOKENS = parseTokens(TOKENS);

export const GMX_SOLANA_GLV_MARKET_TOKENS = [
  'qqq',
  'msft',
  'googl',
  'tsla',
  'amzn',
  'aapl',
  'nvda',
  'spy',
  'meta',
  'mstr',
  'spcx',
];

export const GMX_SOLANA_GLV_METAL_MARKET_TOKENS = [
  'xag',
  'xau',
  'wti',
  'brent',
  'xcu',
  'xpt',
  'xpd',
  'eur',
  'gbp',
  'nzd',
  'aud',
];

export const GMX_SOLANA_GLV_METAL_RWA_MARKET_TOKENS = ['xag', 'xau', 'wti', 'brent', 'xcu', 'xpt', 'xpd'];

export const GMX_SOLANA_GLV_METAL_RWA_COMMODITY_TOKENS = [
  'eur',
  'gbp',
  'nzd',
  'aud',
  'usdjpy',
  'usdcad',
  'usdchf',
  'usdmxn',
];

export const GMX_SOLANA_FOREX_PRECISION_MARKET_TOKENS = [
  'Eurzo3GcsjD9sf32gC4RUu8oUVVmFV2oWqCZvfnzshXM',
  'EurdPiuWJazzqJLKE4Amb1ZQxVkpwEiSKCZfNgXC9Wi4',
  'GbpeVg2NBeL9Q2RDLrYkkkRXNMjaXg4vBZbh2cffH7aG',
  'Audg5JLrnh6tRy6WWPRnZ1kh9xiWr2omtP5xdQRTvqQh',
  'NzdGr62wT4t1xoHdYoVMEdWPb1yg9WQp2rQa34sscgJ',
  'jpygxG9g45Lui4P3GQgfdfNSYcR9985HAcxBRPTHr66',
  'cadDuN2bphC1u8K61ZF9hJCshTRmEyVNd4qiMY28ijo',
  'chfdyavofe2ZXsU67oBnruALSgftfTntvDw3MvyEVRs',
  'mxnZft9hb7nH93UxTApmXzk95Fg6BERE1PPRzwg6SLL',
];
